### ISSUE TITLE
Twilio video not working on react server side rendering

### ISSUE THREAD

**Issue by puspendumandal** [twilio/twilio-video.js#1380]
I have integrated Twilio video chat in a react project. It's working perfectly on the client-side rendering but when we build the code and integrated with server-side rendering, the app crashed. We have gotten an error:

ReferenceError: WebSocket is not defined.

My project techonogy details: 

"react": "^16.13.1",
 node:12
 "twilio": "^3.39.3",
    "twilio-video": "^2.9.0"

we will be very thankful if it resolved. Thanks in advance.

**Comment by Galzk** [comment]
Hey @puspendumandal,
Please try to remove your node_modules directory, then run:
> npm i
and try again
If the issue occurs again, take a screenshot of the error so we can take a look at where the fail happens

Regards
Gal

**Comment by puspendumandal** [comment]
Hey @Galzk,
We have been resolved the WebSocket undefined issue using the "WebSocket" module. Thanks, @Galzk  for your help.

**Comment by beatricetay** [comment]
Hello @Galzk, @puspendumandal, I am currently facing the same issue:
```
ERROR 2022-08-15T02:05:24.302Z [dist/worker/rendererWorker.js] WebSocket is not defined 
ReferenceError: WebSocket is not defined
    at Object../node_modules/twilio-video/src/ws.js (<anonymous>:131470:18)
    at __webpack_require__ (<anonymous>:132073:42)
    at Object../node_modules/twilio-video/es5/twilioconnection.js (<anonymous>:121903:59)
    at __webpack_require__ (<anonymous>:132073:42)
    at Object../node_modules/twilio-video/es5/preflight/getturncredentials.js (<anonymous>:109681:24)
    at __webpack_require__ (<anonymous>:132073:42)
    at Object../node_modules/twilio-video/es5/preflight/preflighttest.js (<anonymous>:109923:28)
    at __webpack_require__ (<anonymous>:132073:42)
    at Object../node_modules/twilio-video/es5/index.js (<anonymous>:102940:23)
    at __webpack_require__ (<anonymous>:132073:42)
ERROR 2022-08-15T02:05:24.302Z [src/server/index.ts] App has failed to start 
```

I am on 
```
"twilio": "^3.63.1",
"twilio-video": "^2.23.0",
```

I have tried removing my node_modules and running `npm i` again, but the issue persists. May I know how you have fixed your issue?
Thank you for your help.

**Comment by Galzk** [comment]
> Hello @Galzk, @puspendumandal, I am currently facing the same issue:
> ```
> ERROR 2022-08-15T02:05:24.302Z [dist/worker/rendererWorker.js] WebSocket is not defined 
> ReferenceError: WebSocket is not defined
>     at Object../node_modules/twilio-video/src/ws.js (<anonymous>:131470:18)
>     at __webpack_require__ (<anonymous>:132073:42)
>     at Object../node_modules/twilio-video/es5/twilioconnection.js (<anonymous>:121903:59)
>     at __webpack_require__ (<anonymous>:132073:42)
>     at Object../node_modules/twilio-video/es5/preflight/getturncredentials.js (<anonymous>:109681:24)
>     at __webpack_require__ (<anonymous>:132073:42)
>     at Object../node_modules/twilio-video/es5/preflight/preflighttest.js (<anonymous>:109923:28)
>     at __webpack_require__ (<anonymous>:132073:42)
>     at Object../node_modules/twilio-video/es5/index.js (<anonymous>:102940:23)
>     at __webpack_require__ (<anonymous>:132073:42)
> ERROR 2022-08-15T02:05:24.302Z [src/server/index.ts] App has failed to start 
> ```
> 
> I am on 
> ```
> "twilio": "^3.63.1",
> "twilio-video": "^2.23.0",
> ```
> 
> I have tried removing my node_modules and running `npm i` again, but the issue persists. May I know how you have fixed your issue?
> Thank you for your help.

Have you tried adding WebSocket library?

**Comment by beatricetay** [comment]
Hello @Galzk, we managed to fix it by providing the WebSocket plugin in our webpack configuration. 
Thank you!
