### ISSUE TITLE
Chrome 92 limits the creation of MediaPlayers

### ISSUE THREAD

**Issue by arunpbk-stayqrious** [twilio/twilio-video.js#1528]
- [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**

Connect to a twilio room, and ask the participants to turn their video on and off for ~ 75 times (in total).

**Expected behavior:**

Should work as expected

**Actual behavior:**

Video stops playing with the error
`[Intervention] Blocked attempt to create a WebMediaPlayer as there are too many WebMediaPlayers already in existence. See crbug.com/1144736#c27`

**Software versions:**

 - [x] Browser(s): Chrome 92
 - [x] Operating System: Mac / Windows
 - [x] twilio-video.js: Probably all versions
 - [x] Third-party libraries (e.g., Angular, React, etc.): React

The culprit seems to be the allocations for dummy media elements created for tracking media track dimensions in mediatrack.js 
https://github.com/twilio/twilio-video.js/blob/master/lib/media/track/mediatrack.js#L233

**Comment by charliesantos** [comment]
Thanks @arunpbk-stayqrious for submitting. We are currently working on this issue.

**Comment by fippo** [comment]
@anna-vasilko girts got a note about this

**Comment by anna-vasilko** [comment]
Despite the upcoming improvement in this SDK (PR #1530), the new limit of MediaPlayers in Chrome 92 may still impact group room applications where participants subscribe to many media tracks. Find more in this chrome ticket 
https://bugs.chromium.org/p/chromium/issues/detail?id=1232649

**Comment by matt-hensley** [comment]
Seeing this issue with automatic track switching enabled with a handful of participants in a room.

**Comment by m-andrew-albright** [comment]
This is impacting our production system, derailing market research video chats, so we will be watching this issue closely.  Please keep us updated with any new information.

(we know Chrome's update is the actual cause, not Twilio's library, so thank you for your efforts in fixing this)

**Comment by makarandp0** [comment]
@matt-hensley @m-andrew-albright, We are [working on a fix](https://github.com/twilio/twilio-video.js/pull/1530) that would mitigate this WebMediaPlayer limit somewhat. And looks like chrome will [soon be updating](https://chromium-review.googlesource.com/c/chromium/src/+/3054514) to increase this limit as well.
Besides these two changes we need application that make a small change as well. Please make sure that after detaching the media tracks in your application set srcObject to null with:
```
  const elements = track.detach();
  elements.forEach(el => {
    el.remove();
    el.srcObject = null;
  });
```
Let me know if this last change helps with your app.
Thanks,
Makarand

**Comment by m-andrew-albright** [comment]
@makarandp0 we JUST pushed our hotfix out doing exactly that -- it fixes the issue in _most_ circumstances, but I believe when enough people manually stop/start their videos it begins to break again.

Thank you!

**Comment by tonymccallie** [comment]
@makarandp0 we tested this fix and it did not correct the issue at all. We are still getting the Blocked attempt error at 70 attaches.

**Comment by makarandp0** [comment]
@tonymccallie, The app change (to set srcObject to null) by itself is not expected to fully resolve the issue. You do need an [upcoming](https://github.com/twilio/twilio-video.js/pull/1530) twilio-video sdk fix as well. I will update here once the fix is released.

**Comment by tonymccallie** [comment]
@makarandp0 is there any timeline on this code coming out? I didn't see it in 2.17.0-rc3

**Comment by BrandonMathis** [comment]
Looks like a fix for this issue was [just released in version 2.15.3](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md#2153-july-28-2021)

**Comment by makarandp0** [comment]
Thanks @BrandonMathis, Yes please try [2.15.3](https://github.com/twilio/twilio-video.js/issues/1528), This fixes the sdk side. Please note that you need the application side fix noted in the changelog as well.

Another good news is chrome is [reverting](https://chromium.googlesource.com/chromium/src/+/f7489718ee87fbef92c59d35d9437cf55466fa2c) the change that limited number of media player, and chrome 92 stable should get an update on Aug 3rd.

**Comment by maciejdudzinski** [comment]
@makarandp0 Can you share the source of Aug 3rd date? 
Do you know if its going to be a patch release that will be downloaded automatically by browsers?

**Comment by tonymccallie** [comment]
@maciejdudzinski it looks to be from here: https://bugs.chromium.org/p/chromium/issues/detail?id=1232649#c85 Not sure about your second question.

**Comment by BrandonMathis** [comment]
Heads-up, Chromium is not reverting the limit to MediaPlayer objects, they are only increasing the cap to 1000 for all devices. 

[Diff of change here](https://chromium.googlesource.com/chromium/src/+/f7489718ee87fbef92c59d35d9437cf55466fa2c%5E%21/)

This will likely resolve this bug for 99.99% of scenarios but failure to properly dispose of video & audio tracks (chrome currently does not distinguish between video and audio streams) could result in this problem arising again.

Please let me know if I am mistaken but, from what I am reading, this limit is still in place but is just very very high at the moment until the chromium team implements a proper fix & publishes an article regarding best-practices when working with media streams.

**Comment by prd-hop-duong** [comment]
I still have the same issue when updating the javascript SDK to 2.15.3 and applying the recommended code, the black screen shows after some minutes with this error.
![twilio-error](https://user-images.githubusercontent.com/63763868/127760272-d14958f9-2ec3-4aa4-b8d3-3445971eff66.png)

**Comment by makarandp0** [comment]
Please note that **Chrome version 92.0.4515.131** is released today with the fix for MediaPlayer limit. Please update your chrome to newer version.

**Comment by makarandp0** [comment]
closing as this is no longer applicable with chrome update - Thank you!
