### ISSUE TITLE
Safari device selection

### ISSUE THREAD

**Issue by michaek** [twilio/twilio-video.js#394]
- [X] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [X] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [X] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [X] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**

```js
TwilioVideo.createLocalVideoTrack({
  deviceId: 'some-other-device-id',
})
```

**Expected behavior:**

I would expect the resolved localVideoTrack to be using the device specified by the deviceId in the constraints, as it did in version 1.x.

**Actual behavior:**

The resolved localVideoTrack in 2.0.0-rc1 uses the same default device, regardless of the deviceId constraint supplied to `createLocalVideoTrack`.

You can reproduce this behavior in `video-quickstart-js`, **but** it is necessary to call `updateDeviceSelectionOptions()` again once video permissions have been requested and granted, or the complete list of video input devices are not available for selection in the UI.

**Software versions:**

 - [X] Browser(s): Safari
 - [X] Operating System: MacOS, iOS
 - [X] twilio-video.js: 2.0.0-rc1
 - [X] Third-party libraries (e.g., Angular, React, etc.): no

**Comment by michaek** [comment]
I should add that I cannot currently reproduce this issue once I have connected with a remote participant.

**Comment by manjeshbhargav** [comment]
Hi @michaek ,

Thanks for opening this issue. Since the last time we corresponded, we have released `twilio-video@2.0.0-beta1`. Since the issue you have filed is against an internal release candidate, can you see if you can reproduce the issue in `2.0.0-beta1`?

```
npm install twilio-video@2.0.0-beta1
```

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by michaek** [comment]
@manjeshbhargav Yes, I was also able to reproduce it in `video-quickstart-js` with `2.0.0-beta1`.

**Comment by manjeshbhargav** [comment]
@michaek ,

Thanks for testing with `2.0.0-beta1`. We are looking into this issue and will get back to you soon.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by manjeshbhargav** [comment]
Hi @michaek ,

I tried to switch between the default webcam and a USB webcam using Safari, and I noticed that `enumerateDevices()` always listed only the default webcam and not the USB webcam. Are you observing this in your tests as well?

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by manjeshbhargav** [comment]
@michaek ,

I ran this [code snippet](https://jsfiddle.net/b9wyx1sc/28/) on Safari v11.1.2 on my mac, and I noticed that it is `getUserMedia()` that actually exhibits the behavior you are describing. I'm going to go through WebKit's bug tracker to see if anyone has filed an issue for this.

It looks like no matter what `deviceId` you provide to `getUserMedia()`, it will always capture from the _first_ `deviceId` in the enumerated list of devices.

I also ran the QuickStart's `Media Devices` example with both SDK versions: `1.13.1` and `2.0.0-beta1`. Both are exhibiting the same unexpected behavior in Safari.

This increasingly looks like an issue with Safari. We will deliberate about this and most probably file a WebKit bug about this.

Thank you for bringing this to our attention.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by michaek** [comment]
Thanks, @manjeshbhargav . I hadn't worked out that it was a problem with the underlying support, and I appreciate you carrying it forward to Safari!

**Comment by manjeshbhargav** [comment]
Hi @michaek ,

We have file this [bug](https://bugs.webkit.org/show_bug.cgi?id=188606) with Safari WebKit to track this issue. I will keep this github issue open until the Safari bug is fixed.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by manjeshbhargav** [comment]
Hi @michaek ,

It looks like this bug has been fixed. I will close this issue.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by michaek** [comment]
@manjeshbhargav Have you verified that the behavior is changed in Safari? I'm still seeing the incorrect behavior that I originally reported, now in Safari 12.0.2.

**Comment by manjeshbhargav** [comment]
Hi @michaek ,

I will try and verify from my end tomorrow.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by michaek** [comment]
@manjeshbhargav Did you verify this was fixed? This issue is still marked closed, but I have not seen the behavior change on my end. Thanks!

**Comment by manjeshbhargav** [comment]
@michaek ,

I have not had the chance to verify this in the latest Safari stable on my end. However, since this is a Safari issue and not a twilio-video.js issue, I have closed this particular github issue. We can still track the Safari bug here.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by michaek** [comment]
Are you sure it's a Safari issue? The linked Safari bug was marked as fixed, which is why you said you closed this issue in January, but this issue does not seem to be affected.

**Comment by manjeshbhargav** [comment]
@michaek ,

I'm pretty sure it is, because we rely on the browser's `getUserMedia()` implementation to choose the correct input device. We don't do anything special in this regard. Also, this is not observable in Chrome or Firefox.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by Govind13100** [comment]
@manjeshbhargav 

I am still facing the issue in 2.0.0-beta5 

the camera switch is not working, the error i am getting is ;
`twilio-video.min.js:100 Uncaught (in promise) TypeError: tracks must be an Array of LocalAudioTrack, LocalVideoTrack, LocalDataTrack, or MediaStreamTrack`

it was working good in 1.14.0 version 

my code is :

`function updateVideoDevice(camIndex) {
  
  const localParticipant = room.localParticipant;
  if (camArray[camIndex] !== '') {
    // get the video
    //console.log(camIndex);
   
    Twilio.Video.createLocalVideoTrack({
      deviceId: { exact: camArray[camIndex] }
    }).then(function(localVideoTrack) {
      const tracks = Array.from(localParticipant.videoTracks.values());
      localParticipant.unpublishTracks(tracks.track);
      //console.log(localParticipant.identity   +" removed track: " +  tracks[0].kind);
      detachTracks(tracks);

      localParticipant.publishTrack(localVideoTrack);
      //console.log(localParticipant.identity +  " added track: " +  localVideoTrack.kind);
      const previewContainer = document.getElementById('local-media');
      attachTracks([localVideoTrack], previewContainer);

    });
  }
}`

**Comment by manjeshbhargav** [comment]
Hi @Govind13100 ,

It seems like you are experiencing some of the breaking changes introduced in 2.x versions. Please refer to this [guide](https://www.twilio.com/docs/video/migrating-1x-2x) in order to migrate your application to 2.x version of the SDK. In your specific example, you can access your existing tracks like this:
```js
const tracks = Array.from(localParticipant.tracks.values()).map(publication => publication.track);
localParticipant.unpublishTracks(tracks);
detachTracks(tracks);
```

Thanks,

Manjesh Malavalli
JSDK Team
