### ISSUE TITLE
Participants in same room not able to see videos and listen audio. Firefox only!

### ISSUE THREAD

**Issue by kumail-raza** [twilio/twilio-video.js#458]
**Issue:** Two participants not able to listen other stream (video,audio), though tracks of the participants in room object are available, also attached with the video tag.

**Scenario:** Two user joins different rooms initially, (being on the same tabs) without disconnecting from the room, then they both join the common room. Both of them not able to listen each other video, audio.

 - [x] I have verified that the issue occurs with the latest twilio-video.js release.
 - [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application the issue is reproduced.
 - [x] I have verified with chrome, its working fine. The issue occurs on FireFox.

**Code to reproduce the issue:**
Following piece of code is the snippet of the quick start code for twilio-video.js, with code to reproduce.

```js
$.getJSON('/token', function(data) {
  // -------:: START - CODE TO REPRODUCE ::----------- 
    var connectOptions = {
        name: "abc",
        logLevel: 'debug'
    };
    Video.connect(data.token, connectOptions).then((room)=>{
       window.room=room;
       console.log("kr110","success")
    }, function(error) {
        log("kr110",'Could not connect to Twilio: ' + error.message);
    });
  // -------:: END - CODE TO REPRODUCE ::----------- 
  
  identity = data.identity;
  console.log(identity);

  document.getElementById('room-controls').style.display = 'block';

  // Bind button to join Room.
  document.getElementById('button-join').onclick = function() {
    roomName = document.getElementById('room-name').value;
    if (!roomName) {
      alert('Please enter a room name.');
      return;
    }

    log("Joining room '" + roomName + "'...");
    var connectOptions = {
      name: roomName,
      logLevel: 'debug'
    };

    if (previewTracks) {
      connectOptions.tracks = previewTracks;
    }

    // Join the Room with the token from the server and the
    // LocalParticipant's Tracks.
    Video.connect(data.token, connectOptions).then(roomJoined, function(error) {
      log('Could not connect to Twilio: ' + error.message);
    });
  };

   //.....
});
```

**Expected behavior:**

Being on the same tab at the same time user can connect to different rooms!

**Actual behavior:**

I believe participant stream could share only at one room! Either a twilio library limitation, or webRtc or the browser.

**Software versions:**

 - [x] Browser(s): FireFox (63.0), Chrome (69+)
 - [x] Operating System: Ubuntu(18.04)
 - [x] twilio-video.js:  [Quickstart](https://github.com/twilio/video-quickstart-js)

**Comment by manjeshbhargav** [comment]
Hi @smkrn110 ,

Thanks for writing in with your issue. I was wondering how you are getting the value for `data.identity`, which you send `/token` in order to create an AccessToken. If for some reason you are using the same string for each user, then when the second user joins, the first user will be kicked out of the Room due to duplicate identity.

Also, it looks like you are setting the first `room` to `window.room`. Can you make sure you're not setting the second `room` to `window.room` in the `roomJoined` callback?

Also, can you give me some Room SIDs which for which I can check our server logs? That will help me in trying to debug this issue further.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by smkrn110** [comment]
Hi @manjeshbhargav,

It is all quickstart app provided by twilio itself. So `/token` provides random identity as server fetch from some **randomname** file, for `window.room` its was just for testing purpose.

My query is could one person connects to, more than one room at the same time for video/audio chatting? 

Since I am not able to achieve it. I like to know; the issue is from twilio api or it is related to webRTC or limitation at browsers end.

Thanks.

**Comment by smkrn110** [comment]
Ok @manjeshbhargav 

Following are the Room SIDs
> smkrn110_room1 : **RMaf8865156ec8d168321ae3178fb6462e**|
> smkrn110_room2 : **RM0402af643d511211a560fe457c37f625**

Issue:
Unable to see the video of remote participants.

Steps to reproduce:
Two person A and B.
1) Both join to room `room1` first.
2) When both of them join 2nd room `room2` without leaving the first room, from the same tab.

then participants (in 2nd room) not able to see remote person video, i have inspect the DOM everything seems to attached also.

**Comment by smkrn110** [comment]
Any progress on this, make sure the issue is only face with the firefox, chrome is working fine. For other browser I have not test it.

**Comment by smkrn110** [comment]
Any progress on this issue?

**Comment by bobin141322** [comment]
Hi Twilio team,

I have the same issue with IOS 11.0.3 -> Firefox: 63.0.3. I only see video but cannot hear audio. When I log Status from audio sent from IOS, using code:

  this.activeRoom.getStats().then(statsReportArray => {
          console.log(statsReportArray); })

I get log: 

participants":[{"sid":"PA63b644971f93565d278641a0f56723f7","identity":"5bd662c9b1c31b000792e990:patient1 Pham:patient","tracks":[{"kind":"audio","priority":"medium","id":"c73b2A4eAcb6cb70Ec27B0c3A3aCC31c",

and 


audioLevel: null
​
bytesReceived: 0
​
codec: null
​
jitter: 0
​
packetsLost: 0
​
packetsReceived: 0
​
ssrc: undefined
​
timestamp: 1543915618943
​
trackId: "c73b2A4eAcb6cb70Ec27B0c3A3aCC31c"
​
trackSid: "MT33cea478e5d36768e22e722c7f077327"

-Room Sid:  "sid":"RM144bbdef4cc3e9614cbf46234b2be9c5","name":"RM144bbdef4cc3e9614cbf46234b2be9c5

I investigate a long time but I cannot find out solution. Please help me check this.

Thanks,
Kieu

**Comment by smkrn110** [comment]
19days passed any update?

**Comment by manjeshbhargav** [comment]
Hi @smkrn110 ,

We have a bug filed for this and it is in our backlog. We will reach out to you once we have made some progress. Please watch this space for updates.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by bobin141322** [comment]
@manjeshbhargav 
Could you help me have a look my issue? Is it the problem from Twilio? I need your confirmation to give answer to client. They are worry about this.
Please!
Thanks,
Kieu

**Comment by manjeshbhargav** [comment]
Hi @bobin141322 ,

I think what you are experiencing is a different issue than the one under discussion here. Your issue looks like a Safari <--> Firefox interop problem. We have released `twilio-video.js@2.0.0-beta4`, which fixes this problem. Please see [this issue](https://github.com/twilio/twilio-video.js/issues/412) for details.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by bobin141322** [comment]
Hi @manjeshbhargav,

I try upgrade to 1.14.2 newest such the comment by syerrapragada in your recommend link. But the issue still exist. I think this is new issue.
I use IOS native App (not use Safari) with IOS 11.0.3 and Firefox: 63.0.3. When I recieve track audio from remote track, sometime I see audio track have property muted = true at track.mediaStreamTrack and I cannot hear any thing (70%).

enabled: true
​
id: "{f6a881d4-3f6e-4194-bdb3-a92c890aa03a}"
​
kind: "audio"
​
label: "remote audio"
​
muted: true
​
onended: null
​
onmute: null
​
onunmute: null
​
readyState: "live"

I tried set enable for remote track: track.enable() but I cannot and get error: "Uncaught (in promise): TypeError: track.enable is not a function.

**Room ID:** "sid":"RM8cd763883568c567337b133af105bfb0"
**audio log:**
audioLevel: null
​
bytesReceived: 0
​
codec: null
​
jitter: 0
​
packetsLost: 0
​
packetsReceived: 0
​
ssrc: undefined
​
timestamp: 1544078875156
​
trackId: "34bA3Ab85AfaFC6fBAdcD49D056D13De"
​
trackSid: "MTfc4a9aa5f748c65c0bd93ab96594cf29"
​
I am trying to enable track for remote audio. Could you give me any advice?

Thanks,
Kieu

**Comment by bobin141322** [comment]
I also test on version 2.0.0 beta4. This issue still happen.

**Comment by manjeshbhargav** [comment]
Hi @bobin141322 ,

In that case, can you open a new issue? It will help us to track progress made on it.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by bobin141322** [comment]
Hi @manjeshbhargav,
Thanks for you reply. I open new issue as your suggestion.
[https://github.com/twilio/twilio-video.js/issues/478](url)
Thanks,
Kieu

**Comment by smkrn110** [comment]
Hi @manjeshbhargav,

What is the progress with the issue?

**Comment by smkrn110** [comment]
@manjeshbhargav 

Any update on the initial prob, reported on this issue? It is experienced only with the firefox.

**Comment by makarandp0** [comment]
Hi @smkrn110, We looked more into this have found the root cause. Looks like the DTLS connection for 2nd participant is not established when two rooms are created from same Firefox tab. We have a solution in mind, and will be trying it out soon. We might have an update in couple of weeks.

**Comment by sherif-hafiz** [comment]
Hi @makarandp0 is there any updates on this issue?

**Comment by makarandp0** [comment]
Hello @sherif-hafiz and @smkrn110 , 
This issue  (VMS-1946) is now fixed. It was issue with the backend, which means you do not need to update the client sdk for the fix.  Please let me know if you still seeing otherwise.

Thanks 
Makarand
