### ISSUE TITLE
Remote media error in Firefox 65

### ISSUE THREAD

**Issue by asimonok** [twilio/twilio-video.js#532]
Hi

I have a problem with twilio in Firefox 65 is Remote video and audio isn't shown.
In latest Chrome 71 it works well. Also twilio works in Firefox 60.5 well. So I suppose this is a new problem. Do you know about this and how it fix?

Console error: 
```
Error: Client is unable to apply a remote media description
```

**Software versions:**

 - [Firefox 65] Browser(s):
 - [MacOS] Operating System:
 - [1.15.1] twilio-video.js:
 - [React] Third-party libraries (e.g., Angular, React, etc.):

**Comment by manjeshbhargav** [comment]
Hi @asimonok ,

Thanks for writing in with your issue. We just released 1.15.2, which might fix your issue. Please try it out and let me know. In the mean-time, can you provide a Room SID which we can use to look at our logs?

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by asimonok** [comment]
@manjeshbhargav Nope:( It wasn't fixed in `1.15.2` version.
Room SID: RM1b5889aab7824e5f726ed9b0a1a4113d

My console output is next. It may be useful.
```
2019-02-08 06:35:36.129Z | WARN in [object Object]: Calling setRemoteDescription with an RTCSessionDescription of type "answer" failed with the error "Failed to parse SDP: SDP Parse Error on line 77:  No webrtc-datachannel token in m= media line, parse failed.
".
``` 
```
2019-02-08 06:35:36.129Z | WARN in [object Object]: The SDP was v=0

o=- 6806022890605485129 2 IN IP4 127.0.0.1

s=-

t=0 0

a=msid-semantic: WMS *

a=group:BUNDLE 0 1 2 3

m=audio 9 UDP/TLS/RTP/SAVPF 109 9 0 8 101

c=IN IP4 0.0.0.0

a=rtcp:9 IN IP4 0.0.0.0

a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level

a=rtpmap:109 opus/48000/2

a=fmtp:109 minptime=10;useinbandfec=1

a=rtpmap:9 G722/8000

a=rtpmap:0 PCMU/8000

a=rtpmap:8 PCMA/8000

a=rtpmap:101 telephone-event/8000

a=setup:active

a=msid:- 4eA27BFCcaFCCe5EB27e20CF9a5b66B8

a=mid:0

a=sendrecv

a=ice-ufrag:xMe+

a=ice-pwd:Nr2EHGQy9YWEyTDil1+U06Vd

a=fingerprint:sha-256 09:18:36:8F:AA:7B:10:DF:89:67:81:E8:EB:78:00:69:E0:5B:84:76:E9:6F:5E:BD:E1:81:AD:E8:52:98:B1:7A

a=ssrc:2199983464 cname:zWzUCTQrSjRs4RV6

a=ssrc:2199983464 mslabel:eDcee84824224863BAa7C30bFbA52fa9

a=ssrc:2199983464 label:4eA27BFCcaFCCe5EB27e20CF9a5b66B8

a=rtcp-mux

m=audio 9 UDP/TLS/RTP/SAVPF 109 9 0 8 101

c=IN IP4 0.0.0.0

a=rtcp:9 IN IP4 0.0.0.0

a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level

a=rtpmap:109 opus/48000/2

a=fmtp:109 minptime=10;useinbandfec=1

a=rtpmap:9 G722/8000

a=rtpmap:0 PCMU/8000

a=rtpmap:8 PCMA/8000

a=rtpmap:101 telephone-event/8000

a=setup:active

a=mid:1

a=recvonly

a=ice-ufrag:xMe+

a=ice-pwd:Nr2EHGQy9YWEyTDil1+U06Vd

a=fingerprint:sha-256 09:18:36:8F:AA:7B:10:DF:89:67:81:E8:EB:78:00:69:E0:5B:84:76:E9:6F:5E:BD:E1:81:AD:E8:52:98:B1:7A

a=rtcp-mux

m=video 9 UDP/TLS/RTP/SAVPF 120 121 126

c=IN IP4 0.0.0.0

a=rtcp:9 IN IP4 0.0.0.0

a=extmap:5 urn:ietf:params:rtp-hdrext:toffset

a=extmap:4 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time

a=rtpmap:120 VP8/90000

a=rtcp-fb:120 ccm fir

a=rtcp-fb:120 nack

a=rtcp-fb:120 nack pli

a=rtcp-fb:120 goog-remb

a=rtpmap:121 VP9/90000

a=rtcp-fb:121 ccm fir

a=rtcp-fb:121 nack

a=rtcp-fb:121 nack pli

a=rtcp-fb:121 goog-remb

a=rtpmap:126 H264/90000

a=rtcp-fb:126 ccm fir

a=rtcp-fb:126 nack

a=rtcp-fb:126 nack pli

a=rtcp-fb:126 goog-remb

a=fmtp:126 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f

a=setup:active

a=msid:- c9aaDfcc0C0Ec79221D9FB87b3dEf4B3

a=mid:2

a=sendonly

a=ice-ufrag:xMe+

a=ice-pwd:Nr2EHGQy9YWEyTDil1+U06Vd

a=fingerprint:sha-256 09:18:36:8F:AA:7B:10:DF:89:67:81:E8:EB:78:00:69:E0:5B:84:76:E9:6F:5E:BD:E1:81:AD:E8:52:98:B1:7A

a=ssrc:3892227032 cname:zWzUCTQrSjRs4RV6

a=ssrc:3892227032 mslabel:eDcee84824224863BAa7C30bFbA52fa9

a=ssrc:3892227032 label:c9aaDfcc0C0Ec79221D9FB87b3dEf4B3

a=rtcp-mux

m=application 0 UDP/DTLS/SCTP 5000

c=IN IP4 0.0.0.0

a=sctpmap:5000 webrtc-datachannel 1024

a=setup:active

a=mid:3

a=sendrecv
```

```
Error: Client is unable to apply a remote media description
```

Please let me know if need some information.

Thanks,
Alex Simonok

**Comment by ksavidetove** [comment]
The new version allows Chrome and Firefox to communicate (video + audio) despite the warning.

There is still an Issue between Firefox and the android Client, the android Client recieves publications with empty tracks

**Comment by innerverse** [comment]
Hi @ksavidetove 

I'm sorry you're running into this issue!  

You're hitting an incompatibility that happens with `peer-to-peer` Rooms, AND DataTracks, with older mobile Twilio Video SDKs Participants and newer Firefox 61+ Participants in the same Room.  

The solution is to upgrade to Twilio Video Android SDK to 3.x+, or iOS SDK 2.3.x+, which has an upgraded WebRTC media engine supporting the new DataChannel format in the SDPs offered by your newer Firefox version.

Hope this helps, 
Seth

**Comment by manjeshbhargav** [comment]
Hi @asimonok ,

Please refer to my colleague's comment above regarding older android sdk versions.
Please let me know if upgrading to the latest android sdk solves the problem for you.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by asimonok** [comment]
Hi @manjeshbhargav,

We've updated Android SDK to 3rd version and it solved our problem.
Thanks a lot for your help.

This issue can be closed.

Thanks,
Alex
