### ISSUE TITLE
Empty video when tracks are added after joining room

### ISSUE THREAD

**Issue by rissem** [twilio/twilio-video.js#80]
A user, Jane, first joins the room with `Twilio.Video.connect(token, {audio: false, video: false})`. 

Jane later adds the audio and video tracks using `room.localParticiapant.addTrack(track)` w/o error.

All other participants currently in the room see a black video box instead of Jane.

Participants that join the room after Jane has added her audio/video tracks see a proper video of her.

Happy to provide any additional clarification. Thanks!

**Comment by markandrus** [comment]
Hi @rissem,

Sorry you hit this! This is a two-part bug: a server-side fix has been deployed, and we are working on the client-side fix for the remainder. The specific fix is [here](https://github.com/twilio/twilio-video.js/commit/6edf705e46524ae1a79d8c29d501c1eae8e90ea9) and is about to go through our QE process before we release it.

Thanks,
Mark

**Comment by markandrus** [comment]
@rissem,

This should be fixed in 1.0.0-beta7. Would you mind retesting with it?

Thank you,
Mark

**Comment by iaptsiauri** [comment]
@markandrus 
I have updated to the 1.0.0-beta7 but it seems I still experience the issue. 

```
      room.participants.forEach(function(participant) {
        previewContainer = document.getElementById('remote-caller');
        attachParticipantTracks(participant, previewContainer);
      });
```
but as soon as I wrap the code in 1 second timeout everything works.  This is the excerpt from the quick start application.

**Comment by rissem** [comment]
Fixed for me. Thanks!
