### ISSUE TITLE
Importing Twilio-Video breaks page in Firefox 70+ with RTC disabled

### ISSUE THREAD

**Issue by graue** [twilio/twilio-video.js#811]
- [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**

```js
import TwilioVideo from 'twilio-video'
```

...in Firefox 70+ with `media.peerconnection.enabled` set to `false` in `about:config`.

**Expected behavior:**

Twilio SDK should see that WebRTC is not available and still allow other functions on the page to work.

**Actual behavior:**

Entire page is brought down _at import time_ by undefined reference to global `mozRTCSessionDescription` (https://github.com/twilio/twilio-webrtc.js/issues/106).

When I tried patching around this, I hit [another undefined reference](https://github.com/twilio/twilio-webrtc.js/blob/7716be1/lib/rtcpeerconnection/firefox.js#L257) to `RTCPeerConnection`.

These references both need to be fixed to ensure importing Twilio-Video, even when WebRTC is disabled, doesn't break non-call related functions on the page. The simplest fix would seem to be accessing both via `window`.

**Software versions:**

 - Browser(s): Firefox 70+
 - Operating System: Linux, but likely all
 - twilio-video.js: 2.0.0-beta15
 - Third-party libraries (e.g., Angular, React, etc.): not relevant

**Comment by makarandp0** [comment]
Thank you for finding and reporting this issue @graue! 
I have filed a bug for this - we should get to this soon. (JSDK-2591)

Thanks,
Makarand

**Comment by makarandp0** [comment]
https://github.com/twilio/twilio-webrtc.js/pull/new/JSDK-2591-fix-loading-errors

**Comment by makarandp0** [comment]
Fixed in 2.0.0-beta16 release (https://github.com/twilio/twilio-video.js/releases/tag/2.0.0-beta16).

**Comment by cesc1989** [comment]
I faced this same issue again.

```
TypeError: 'get peerIdentity' called on an object that does not implement interface RTCPeerConnection.
```
**Versions**

- Firefox 74.0
- Twilio video 2.0.0-beta16
- Mac OS Mojave 10.14.6

**Comment by cesc1989** [comment]
Using the CDN version let me continue "importing" twilio-video although the error still shows up.

```
TypeError: 'get peerIdentity' called on an object that does not implement interface RTCPeerConnection.twilio-video.min.js:55:5388
```

**Comment by rishab1065** [comment]
@makarandp0  getting this error again in Firefox
`Unhandled Rejection (TypeError): 'get peerIdentity' called on an object that does not implement interface RTCPeerConnection.`

firefox version : 76.0.1 64bit
twilio-video : 2.0.1
Mac OS Mojave: 10.14.6

**Comment by deep-link** [comment]
facing same issue. any fix for this issue?

**Comment by rishab1065** [comment]
@deep-link Use Twilio CDN to fix this issue

**Comment by cesc1989** [comment]
@deep-link I could use the NPM package by importing it this way:

```javascript
import * as Video from 'twilio-video/dist/twilio-video';
```

**Comment by MartijnHols** [comment]
Still occurs in firefox 78, twilio-video 2.7.0.

**Comment by amishshah** [comment]
Still occurs on Firefox 80, twilio-video 2.7.2. I'm using twilio-video with create-react-app.

This issue doesn't appear for me until switching to Firefox's built-in mobile emulator, and then I get the following error:

![image](https://user-images.githubusercontent.com/10330923/93317105-f3ad4d00-f804-11ea-85cb-55985cdf2871.png)

**Comment by marcelloma** [comment]
This is still happening on firefox 86 and twilio-video 2.10.0.

**Comment by makarandp0** [comment]
sorry for super late reply on this. @marcelloma - Can you give me some repro steps. I am sure I am missing something - I tried loading twilio-video on Firefox 86 and did not see this error - even with `media.peerconnection.enabled` set to false in about:config

Thanks,
Makarand

**Comment by MonstraG** [comment]
> 
> 
> sorry for super late reply on this. @marcelloma - Can you give me some repro steps. I am sure I am missing something - I tried loading twilio-video on Firefox 86 and did not see this error - even with `media.peerconnection.enabled` set to false in about:config
> 
> Thanks,
> Makarand

Have you tried in Responsive Design Mode with some phone selected?

**Comment by Galzk** [comment]
Here's my workaround:

https://user-images.githubusercontent.com/34302982/112455642-96b9c300-8d62-11eb-9fb2-fd3ea3a3fdd4.mp4

**Comment by makarandp0** [comment]
Thanks @Galzk for the screen recording. Got the repro now. Very interesting that Firefox does this :). I have opened an internal ticket (VIDEO-4654) to track this issue. We should be able to get to it soon. 
Thanks,
Makarand

**Comment by makarandp0** [comment]
Hello @Galzk, This issue is fixed in 2.14.0 - There are also other [significant improvements](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md#2140-may-11-2021) in 2.14.0. Please check it out!
Thanks
Makarand
