### ISSUE TITLE
iOS Safari Does not always play all remote audio

### ISSUE THREAD

**Issue by etown** [twilio/twilio-video.js#922]
- [ x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x ] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x ] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x ] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

On iOS sometimes remote audio is not being played.

**Expected behavior:**
All remote audio is played

**Actual behavior:**
Sporadically when are you attached it does not play on iOS. The situation is usually a larger group room 3 to 6 participants. Occasionally one participant will not hear the remote audio of another. In this case, calling pause and then play on the video element triggers the audio to play back correctly.  Calling play alone will not revive the audio. It seems like it could be related to auto play, but it only affects a single participate.

**Software versions:**

 - [x ] Browser(s): Safari
 - [x ] Operating System: iOS 13
 - [x ] twilio-video.js: latest
 - [x ] Third-party libraries (e.g., Angular, React, etc.): React

**Comment by etown** [comment]
Fully reproducible with https://github.com/twilio/twilio-video-app-react

**Comment by rkiller** [comment]
We are having big issues with iPhones using twilio-video.js We believe the problem is with the attachment of the local audio track on the iphone. I would say about 30% of calls fail randomly. We tried setting the workaroundWebKitBug180748 flag, but no luck, the problem persists. Any help in this regard is appreciated.

**Comment by anna-vasilko** [comment]
Hey @rkiller 
We are able to reproduce random audio issues on mobile Safari. Investigating.
Not sure if you are hitting the same problem though. Any chance you could share a room sid? And browser logs from mobile Safari would be ideal. 

Also please check out known issues for Safari here, maybe you are hitting one of them. 
https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md
- Working around the browsers' autoplay policy 
- Mobile Safari Participants on iOS 13.0.1 sometimes fail to send audio

**Comment by rkiller** [comment]
Hi Anna:

Room SID would be RM3862e1ca8177041eaf3380d0d593390c

I have loglevel debug enabled, but getting the output though logrocket.com which makes it difficult to paste and record it. If you really need the console logs I’ll try a different way. Just let me know.

Best,

Roger

**Comment by manjeshbhargav** [comment]
Hi @rkiller ,

I investigated the Room SID you shared with us, and it looks like iOS Safari muted and unmuted its audio track a couple of times, and later started adding more audio tracks. Is that by design? I ask because in iOS, once you create a second track, audio will stop flowing to the first track. It is recommended to stop and unpublish the existing track before publishing the new track.

In case of the first audio track, our logs indicate that no bytes were sent by iOS Safari. This can happen if another app (which may be backgrounded) has reserved the microphone. We are looking at ways to detect this and maybe either come up with a workaround or raise a warning.
We'll let you know once we know more.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by rkiller** [comment]
Thank you for the reply Manjesh. 

This was by design. Once we recognize that the audio is not working, we ask the counterparty you to mute and unmute their tracks. There is code on the client side that is supposed to tear down the track and recreate it with createLocalAudioTrack(webkitworkaround10784 (sp?): true). 

However this solution did not work. Are you aware of any work arounds for this iOS bug?

**Comment by rkiller** [comment]
Another one. Please see: RM4c5f8dadf8e90c9ded52b1f707ed07f8

**Comment by etown** [comment]
> Hey @rkiller
> We are able to reproduce random audio issues on mobile Safari. Investigating.
> Not sure if you are hitting the same problem though. Any chance you could share a room sid? And browser logs from mobile Safari would be ideal.
> 
> Also please check out known issues for Safari here, maybe you are hitting one of them.
> https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md
> 
> * Working around the browsers' autoplay policy
> * Mobile Safari Participants on iOS 13.0.1 sometimes fail to send audio

I am able to reproduce with your exact sample code and I am certain It is not related to the listed issues in your documentation. It’s not autoplay related and it’s not related to webkitworkaround10784. Any update would be very much appreciated.

**Comment by anna-vasilko** [comment]
Hey @etown The team can reproduce in the same way as you do, where pause() and play() fixes the problem. So far we could not find a good way to detect and workaround the issue programmatically because bytes are flowing on the track when it happens. Even though it looks like a mobile Safari issue, it's a top priority for our dev team to find a workaround. We'll keep you posted.

**Comment by anna-vasilko** [comment]
@etown We have got a potential workaround, our QE is verifying it tonight. Stay tuned.

**Comment by manjeshbhargav** [comment]
Hi @etown ,

Thanks for your patience. We have been working round-the-clock trying to find out a programmatic way of detecting this issue. We extracted audio samples from the RemoteAudioTrack to see if they are all zeroes, but found out that the samples had non-zero values. All relevant properties of the track and the audio element were as expected. So, code-wise, there is no difference that we could find between the normal case and this issue.

However, when this issue does happen, calling `pause()` and `play()` on the `<audio>` element did re-direct the bytes to the loudspeaker. After some research, this looks like an existing Safari bug: https://bugs.webkit.org/show_bug.cgi?id=196539.

So, at this stage, we recommend that you attach the audio track to a separate `<audio>` element and then call `pause()` and `play()` if you detect iOS Safari as the browser:

Option 1:

```js
const audioElement = remoteAudioTrack.attach();
divContainer.appendChild(audioElement);

if (/* iOS Safari */) {
  function once(el, event) {
    return new Promise(resolve => {
      el.addEventListener(event, function onEvent() {
        el.removeEventListener(event, onEvent);
        resolve();
      });
    });
  }

  once(audioElement, 'play').then(() => {
    const onPause = once(audioElement, 'pause');
    audioElement.pause();
    return onPause();
  }).then(() => {
    return audioElement.play();
  }).then(() => {
    console.log('Pause/play called!');
  });
}
```

Option 2:

```js
const audioElement = remoteAudioTrack.attach();
divContainer.appendChild(audioElement);

if (/* iOS Safari */) {
  audioElement.pause();
  audioElement.play();
}
```

While **Option 1** mimics the manual pause/play sequence in the console, **Option 2** is more straight-forward. Please try them out and let us know if any one option works for you.

We also recommend that you include a "media check" UI prior to joining a Room where the user selects and tests the microphone and camera. That way, you can be sure that your app has access to the media devices.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by etown** [comment]
Thank you. However, I’ve already tried pausing and playing at different points in the attachment process and have never been able to reliably have it work. I will try your options, have you been able to confirm that option 1 or 2 consistently works? Would you have a full sample if it’s working reliably?

**Comment by manjeshbhargav** [comment]
Hi @etown ,

We did some testing yesterday on option 2, and today we are testing option 1. So far things look promising. Because this issue is intermittent, and we know that pausing and playing manually in the console works, I would recommend you start with option 1, which closely mimics the manual workaround. Once we have verified option 1, we will update the react app code in the master branch.

Thanks,

Manjesh

**Comment by etown** [comment]
Ok, I hope you can continue test and then update with findings because I have tried this approach and it might have reduced occurrences but it definitely still was happening for me.

**Comment by mding5692** [comment]
Following this topic as we had a similar issue, not sure if related, Room SID: RM13db0a5e7e4dc36d2d683938d9098905

Should we just recommend our customers to not use Safari for the meantime and switch to Chrome?

**Comment by manjeshbhargav** [comment]
Hi @mding5692 ,

It looks like iOS Safari did not send any audio bytes to the Desktop Chrome participant. This is most likely because the mic was being used by another app. This can happen even with YouTube being open. I suggest that you add a pre-connect mic and camera check UI to make sure both the devices are working properly before putting them into the Room. You can use the [Web Audio APIs](https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API/Visualizations_with_Web_Audio_API) to grab audio samples, and if the samples are 0, then you know that your mic is being used by another app, and you can then recommend the user to close other apps and restart iOS Safari.

If you don't want to deal with the Web Audio APIs directly, here is an [NPM module for a volume level indicator](https://www.npmjs.com/package/volume-meter). If iOS Safari cannot capture audio, then the volume level will always be 0.

Please let me know if this works for you.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by fictorial** [comment]
This seems to be working for us but of course less than ideal.  We aren't too keen going live with this and don't want to lose time invested in moving to another provider.

```javascript
    if (isMobileSafari()) {
      setInterval(function () {
        $('audio').each(function () {
          this.pause();
          this.play();
        });
      }, 2000);
    }
```

**Comment by manjeshbhargav** [comment]
Hi @fictorial,

You only need to pause and play once. I don't think doing this more than once is required.

Thanks,

Manjesh

**Comment by fictorial** [comment]
It didn't work consistently to just do it once unfortunately.

**Comment by manjeshbhargav** [comment]
Hi @fictorial,

Can you try pausing after ensuring that the audio element is playing, and then playing after ensuring the audio element has paused?
```js
if (isMobileSafari()) {
  $('audio').each(function() {
    this.addEventListener('pause', function onPause() {
      this.removeEventListener('pause', onPause);
      this.play();
    });
  });
}
```

**Comment by anna-vasilko** [comment]
All, based on our testing, the suggested workarounds seem to reduce the frequency of the issue but do not fix it completely, unfortunately.
We have found another lead, we suspect the issue is specific to React rendering of audio on iOS Safari. We will be testing alternative ways of rendering to confirm that.

We continue digging and reached out to Safari team. So far they pointed to several related (but not the same) iOS Safari audio bugs, which got fixed by them recently.
https://bugs.webkit.org/show_bug.cgi?id=208516
https://bugs.webkit.org/show_bug.cgi?id=209411
https://bugs.webkit.org/show_bug.cgi?id=209412

**Comment by fictorial** [comment]
FWIW I am not using React. Hope that helps.

**Comment by etown** [comment]
@anna-vasilko @fictorial is correct. The simple solution you are recommending does not solve the issue. Pausing and restarting every two seconds results and obviously very choppy audio. So there is currently no workaround known, please keep us updated. Thank you

**Comment by manjeshbhargav** [comment]
Hi @etown ,

Since you are working with our React App, we also noticed another thing. Since we move the active speaker to the top of the thumbnail list, we noticed that the `<audio>` elements were removed and added again to the DOM, which increased the likelihood of triggering this issue by a lot. So, we made a [change](https://github.com/twilio/twilio-video-app-react/pull/124/files) to the app to only add the `<audio>` element to the DOM once. Our QE team tried reproducing this issue and were able to succeed in only 1 out of 40 Rooms.

Please try this out with your app and let us know what you find.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by anna-vasilko** [comment]
Here is a Safari ticket tracking this issue. Safari team is investigating. https://bugs.webkit.org/show_bug.cgi?id=196539

Even though it's not a Twilio SDK bug, I'll keep this ticket open while we are waiting for updates or workarounds from Safari.

**Comment by fictorial** [comment]
Have you guys considered these workarounds?

**Comment by anna-vasilko** [comment]
@fictorial The suggested workaround from Comment 16 does not solve the issue based on our testing.
We evaluated many workarounds, what worked the best so far is to minimize the amount of audio rendering in the app, that significantly reduced the frequency of the issue in our internal apps, Manjesh described it [above](https://github.com/twilio/twilio-video.js/issues/922#issuecomment-608096969).
According to Safari team, the issue is caused by a capture failure that is not notified to the page. That makes it undetectable programmatically. I am afraid there is nothing else we can do other than wait for a fix in iOS Safari browser itself.

**Comment by bjm88** [comment]
Hi @anna-vasilko any update on this issue?  We continue to see this Safari Audio Bug.  We are trying the toggle solution, but seems many are finding that not fixing it.  The render avoidance issue isn't so clear to us, but will also give it a try.  Has Apple confirmed they are working on, any ETA?  Seems like a major issue if effecting basically all iPhone users for WebRTC.

**Comment by manjeshbhargav** [comment]
Hi @bjm88 ,

Safari hasn't committed to any hard timeline to fix this. We'll reach out here once we have more information.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by techcouncilbox** [comment]
Hi @manjeshbhargav,

Do you know if ios 13.5 (launched recently) fixes these problems?

**Comment by anna-vasilko** [comment]
Hey @techcouncilbox Our quality engineering team is measuring reproducibility on the latest 13.5 today. I'll share results tomorrow!

**Comment by anna-vasilko** [comment]
Hey @techcouncilbox 
This audio rendering issue is still reproducible with 13.5. 
Safari team at Apple let us know they are still working on it and they'll keep us posted.

Happily we see it being less reproducible with more recent iOS/Safari versions 13.4 and up, most likely because of performance improvements in those versions.
Here is the issue reproducibility as measured by our QE team on iOS versions 13.4 and 13.5:  
Group rooms - occurs in 0-2 rooms out of 50
Peer to peer rooms -  occurs in 6-9 rooms out of 50.
The issue normally goes away on refresh/re-joining the room.

The best way to track the state of known iOS Safari audio issues is by following this ticket. I am going to close this one as a duplicate of it. https://github.com/twilio/twilio-video.js/issues/941

**Comment by Orbit-Akhil-Puri** [comment]
> Hi @etown ,
> 
> We did some testing yesterday on option 2, and today we are testing option 1. So far things look promising. Because this issue is intermittent, and we know that pausing and playing manually in the console works, I would recommend you start with option 1, which closely mimics the manual workaround. Once we have verified option 1, we will update the react app code in the master branch.
> 
> Thanks,
> 
> Manjesh

Hi Manjesh,

I am also facing  same issue with IOS devices . WhenI need to put above code in react app. I am completely stuck because of above issue

**Comment by rajeyecarelive** [comment]
Just checking if there is a fix for this issue? Since this is closed, what is the workaround or a fix? Pause() Paly() doesn't works at all for us.

**Comment by techcouncilbox** [comment]
It is closed due to thread about this issue is here: https://github.com/twilio/twilio-video.js/issues/941

**Comment by Orbit-Akhil-Puri** [comment]
Hi Team,

Please let me know is thee any alternate fix for above. We already done a commitment about release with clients and this bug is becoming in major bottleneck.

Thanks & Regards,
Akhil Puri

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by anna-vasilko** [comment]
Hey all, 
Safari team from Apple communicated that this issue is fixed in the latest iOS beta 13.5.5, which is available for testing with the iOS dev account. Our internal testing confirmed the fix.

**Comment by bjm88** [comment]
> Hey all,
> Safari team from Apple communicated that this issue is fixed in the latest iOS beta 13.5.5, which is available for testing with the iOS dev account. Our internal testing confirmed the fix.

hurrah!

**Comment by ryango** [comment]
I still see this on 13.6 beta. Fixes itself when I background Safari. Audio element reports playing. Reproduces very frequently when remote participant is Chrome on Mac. Pause/play seems to play one buffer then it gets back into the bad state.

**Comment by AishwaryaBhaskaran99** [comment]
While recording audio , and clicking mute/unmute does not really work.Any Workarounds for this?
