### ISSUE TITLE
Known audio issues in iOS Safari browser

### ISSUE THREAD

**Issue by anna-vasilko** [twilio/twilio-video.js#941]
There is a couple of known audio issues in the iOS Safari browser. Please see the corresponding Safari tickets and our recommendations. 

**1. Remote audio does not play occasionally.**
**Safari ticket:** https://bugs.webkit.org/show_bug.cgi?id=196539 (it has been escalated to Safari team)
**Recommendation:** There is no good workaround so far, you can find few recommendations on how to reduce its occurrence on this Github ticket https://github.com/twilio/twilio-video.js/issues/922.

**2. RemoteParticipants can't hear audio from iOS Safari (Safari sending zero bytes).** 
**Safari ticket:** https://bugs.webkit.org/show_bug.cgi?id=208516. 
**Reason:** This happens if the mic is taken over by another application or after the application is in the background. 
**Recommendation:** We recommend that you add a pre-call mic and camera check UI to make sure both the devices are working properly before connecting the user into the Room.
You can use the Web Audio APIs to grab audio samples, and if the samples are 0, then you know that your mic is being used by another app, and you can then recommend the user to close other apps and restart iOS Safari. If you don't want to deal with the Web Audio APIs directly, here is an NPM module for a volume level indicator. If iOS Safari cannot capture audio, then the volume level will always be 0.

Other audio-related bugs in iOS Safari:
Improper audio routing - https://bugs.webkit.org/show_bug.cgi?id=196539
Audio interruption issue - https://bugs.webkit.org/show_bug.cgi?id=209411
Audio mute/unmute issue https://bugs.webkit.org/show_bug.cgi?id=209412)

**Comment by bjm88** [comment]
+1.  We are eagerly awaiting a fix for this from Twilio or Safari.  We are able to reproduce #1 remote audio not playing on iOS Safari iPhone setups a lot, like 50% of the time.  This is after doing the suggested work arounds of pause/play and avoiding rerendering of <audio> tag.

**Comment by manjeshbhargav** [comment]
@bjm88 

We are in touch with Safari WebKit engineers and will keep you posted on any future updates from them regarding these issues.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by XuanyuHu** [comment]
@manjeshbhargav 
Could you help to check for the iPadOS as well?
We have clients reported that the iPad Safari is losing audio as well.
Around 90% time, refreshing the Safari Browser will resolve the issue (audio will work).

**Comment by bjm88** [comment]
thanks @manjeshbhargav - ya fyi We escalated with Apple and put in developer ticket with them, 734340602, if you need to reference.

We had both the "option #2" pause/play and the "avoid rerender by adding directly to dom" audio track attachment workarounds in and were still able to reproduce the issue about 30-50% fo the time.  We actually toook out the pause/play and just left the attachment change and are seeing better results, seems like more like 1 out of 10, but still early in the testing.

**Comment by manjeshbhargav** [comment]
@XuanyuHu , @bjm88 ,

In our [best practices guide](https://www.twilio.com/docs/video/build-js-video-application-recommendations-and-best-practices), we recommend that you provide an audio level indicator for your local and remote audio tracks, so that the application can recommend users to reload the app or restart their browsers. Please take a look at the recommendations and apply them where appropriate.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by bjm88** [comment]
thx @manjeshbhargav we are planning to do that.  We did notice the issue happens more on older iPhones 6/7 and less on X.  Also our QA eng found she could reproduce a LOT on normal iPhone settings with Siri enabled, but when disabling Siri could not reproduce at all.  Perhaps something to rely to apple.

**Comment by anna-vasilko** [comment]
@bjm88 Thank you so much for sharing your observations, I relayed it to the Safari team at Apple

**Comment by elebumm** [comment]
I have the same issue with #2 where the entire calls works apart from audio being sent from the iOS device to the participant (Chrome usually but anything really.)

I was able to create this issue on my iPhone 11 Pro Max doing the following:

- Go to your web application on safari
- Go back to the home screen (while having safari in the background)
- Use an audio input of some sort. (I just said hi to Siri)
- End that audio input
- Go through the typical flow of how your application starts (accept permissions etc)
- So far, 100% of the time it detects audio device but doesn't capture audio (or send)

I can fix this by exiting safari and opening again.

I feel like this happens when Safari is open the entire time. I had it happen when safari was in the background for at least 5 minutes. This could be depending on what "type" of person you are:

- Someone who has all of their applications open in the background constantly (my dad)
- Someone who exists as soon as their done (me).

I am on iOS 13. Let me know if anyone finds issue running into it this way as well.

I have temporarily fixed this by adding tests mentioned by @anna-vasilko before video and audio is enabled and gives instructions as to how to fix it.

Let me know if this was helpful for anyone.

**Comment by ChrisEelmaa** [comment]
I can produce audio issues in almost 99% of time in 1v1 direct rooms between ios devices, here is how:

1) I force everyone to go through mic / video check.

2) After they have gone through the mic check together, their browsers will automatically refresh by using location.reload(), (I thought I am clever: that would ensure there is no old garbage left behind, such as some streams floating around, basically start from completely clean sheet)

3) They now press Join room button and will be joined using Twilio.connect()

4) Neither party can hear each other. If they both refresh their browsers manually, they start hearing each other.

Basically this approach backfired. It looks like using location.reload() will almost guarantee that there is no audio anymore. Perhaps this method can be used by other people to get into the state of "there is no audio" very easily.

For now I have removed the window.location.reload() and added a button of "I can't hear the other person" which will show popup which tells *both* people to refresh their browser. I've also use only one single audio element throughout the app which is decoupled from react:

```

audioService.setRef(document.getElementById('audio-element'));

render(
  <App />,
  document.getElementById('root'),
);
```

**Comment by hmheng** [comment]
im trying to use the proposed workaround in #922 
with pause() and play().
however, Mac Safari tell me it is NotAllowedError, similar to the issue : https://github.com/mediaelement/mediaelement/issues/2410

**Comment by rajeyecarelive** [comment]
Workaround doesn't works at all. iPad Pro and iPhone devices - none produced any audio at all.

**Comment by Orbit-Akhil-Puri** [comment]
This bug is majorly coming on devices with ios version < 13.0.

**Comment by everbslab** [comment]
Same thing with iOS/Safari up 13.4 - no remote audio available when participiant is on iPhone

**Comment by elebumm** [comment]
[Have you guys tried seeing if my comment is what is causing this issue?](https://github.com/twilio/twilio-video.js/issues/941#issuecomment-622481673)

Since this bug is in the hands of Apple who have identified it as part of their issue, perhaps the best option is to create a little dialog box for users to restart safari and try to run the application again. I know it's not the best answer but I found that solution to work best and have reduced no audio signal connections by almost 95%. 

Until Apple fixes this issue on the next iOS update, it might be the best solution for now. Sadly, since the fix to safari will require a software update, the problem might still persist throughout iOS 13.x

**Comment by hmheng** [comment]
@elebumm thanks for your response. Understand that bug could be coming from iOS Safari team for iOS devices. May I know if it is the same issue for Safari on Mac devices? Or i should raise separate ticket?

**Comment by anna-vasilko** [comment]
@hmheng Two audio issues described in this ticket are specific to mobile Safari.

**Comment by anna-vasilko** [comment]
All, quick update on state of these two issues:
**1. Remote audio does not play occasionally in iOS Safari browser**
**Latest status:** Safari team at Apple is working on a fix, they let us know it should be testable within a few weeks
**Reproducibility** 
- The issue is less reproducible with iOS/Safari versions 13.4 and up
- Group rooms - occurs in 0-2 rooms out of 50
- Peer to peer rooms - occurs in 6-9 rooms out of 50

**2. RemoteParticipants can't hear audio from iOS Safari (Safari sending zero bytes)**
**Status**: We found a workaround for this Safari bug and plan to ship it in the next release of our SDK. The workaround is expected to work on iOS Safari versions 13.4+.
**Reproducibility**: This is 100% reproducible in cases when other applications like Siri or Youtube takes over the mic. Example: Join a video room, share audio/video -> Open Siri and talk to it -> come back to your video application -> now your mic will be sending silence to the room, remote party will not be able to hear you.
**Recommendation**: We recommend that you add an audio indicator UI in your app so that your users case see that something is wrong with the mic or they are sending silent audio.

Follow this guide with the best practices from our dev team to avoid media issues in your applications https://www.twilio.com/docs/video/build-js-video-application-recommendations-and-best-practices

**Comment by romanalyoshkin** [comment]
@anna-vasilko Hi Anna, we are looking at a possible solution for the video/audio calls and faced that issue with our existing solution. I'm curious how reliable is your workaround and when do you plan to make it public?

**Comment by makarandp0** [comment]
Hello @romanalyoshkin - The [safari audio workaround](https://github.com/twilio/twilio-video.js/tree/2.6.0-rc1/dist) is in test, and we are hoping to release this week. If you are interested you can try it out, and let us know how it works out for your application.

Thanks,
Makarand

**Comment by bjm88** [comment]
hi @makarandp0 are you talking about work around for issue #2 above right, not #1 ?

**Comment by makarandp0** [comment]
@bjm88 yes, the workaround is only for Webkit Bug: https://bugs.webkit.org/show_bug.cgi?id=208516

**Comment by RusseII** [comment]
> Group rooms - occurs in 0-2 rooms out of 50
Is that for iOS/Safari versions 13.4 and up, or for the older versions?

**Comment by everbslab** [comment]
Please be aware that using twilio-video https://github.com/twilio/twilio-video.js/tree/2.6.0-rc1 requires update with https://raw.githubusercontent.com/twilio/twilio-webrtc.js/4.3.0-rc1/lib/util/index.js.

Otherwise there will be an error with 

`var _require = require('@twilio/webrtc/lib/util'),
    ...
    isWebRTCSupported = _require.support;`

Anyway now I get in Windows/Chrome the following error with 2.6.0.-rc1
![image](https://user-images.githubusercontent.com/970419/83523428-66234700-a50c-11ea-92b4-e4e7d6957af9.png)

**Comment by everbslab** [comment]
@makarandp0 
We just had a test with iPhone/Safari workaround version which comes from 2.6.0.-rc1. No luck. Still iPhone user unable to unmute himself using iPhone.

**Comment by anna-vasilko** [comment]
@everbslab Yes, the 2.6.0.-rc1 went through a testing cycle and we found that the workaround is not working on some of the iOS versions, the team is investigating.

**Comment by anna-vasilko** [comment]
Hi all,
Here is an update on the state of things:

**1. Remote audio does not play occasionally in iOS Safari browser**
Safari team from Apple communicated that it got fixed in the latest iOS beta version 13.5.5. Our internal testing confirmed the fix. 

**2. RemoteParticipants can't hear audio from iOS Safari after using another app (ex. Siri, Youtube etc)**
We continue working on a workaround in the SDK, the first RC did not pass testing. Second one is baking.

Note that both described issues are rarely reproducible. If you hit an audio problem all the time, make sure to go through [this guide](https://www.twilio.com/docs/video/build-js-video-application-recommendations-and-best-practices) to avoid most common pitfalls

**Comment by RusseII** [comment]
@anna-vasilko are you able to share exactly what the apple team said or where they posted that they fixed the issue? 

We have a client who is waiting for these issues to be fixed to move past the pilot period, and having that to share with them would be very useful.

**Comment by anna-vasilko** [comment]
@RusseII You can see public update from Apple on the WebKit bug representing this particular issue https://bugs.webkit.org/show_bug.cgi?id=198545

**Comment by hameshiv** [comment]
@anna-vasilko I'm joining the thread because of a new and different issue.

I work for a company in the field of tele-audiology (remote hearing tests), using Twilio for video-conferencing on our web solution.
We currently face an issue with our solution on iOS: during a conference call, our signal generated using webaudio is played in both channels as mono. Whenever we stop the video (using the red camera in url toolbar), the sound is played on the right channel, as intended. Back to the video, it's on both channels again.

Any help would greatly be appreciated. Thanks!

**Comment by RusseII** [comment]
> 2. RemoteParticipants can't hear audio from iOS Safari after using another app (ex. Siri, Youtube etc)
We continue working on a workaround in the SDK, the first RC did not pass testing. Second one is baking.

@anna-vasilko is there any estimates on when this will be rolled out?

**Comment by anna-vasilko** [comment]
@hameshiv  Thanks for writing in! The issue you describe sounds different and new to us. We will be happy to look at it, but could you pls open a separate github ticket for it.

**Comment by anna-vasilko** [comment]
@RusseII We are still working on that issue (#2 from the ticket description). It is on top of our priorities. So far the workaround in the SDK seemed to improve the behavior in some cases/ iOS versions, but stumbled upon another iOS Safari browser issue. We are investigating, talking to Apple team and doing everything to improve it. We are aiming for a release within a week if no more surprises. I will keep you posted.

**Comment by ryango** [comment]
I still see #1 on 13.6 beta. Fixes itself when I background Safari. Audio element reports playing. Reproduces very frequently when remote participant is Chrome on Mac. Pause/play seems to play one buffer then it gets back into the bad state.

**Comment by ryango** [comment]
Zooming the page also fixed it? Audio element emits no events when it fixes itself. Previous play() call reports success

**Comment by RusseII** [comment]
@ryango how commonly is "very frequently" ? Is it happening more commonly than the reported `0-2 rooms out of 50`?

**Comment by ryango** [comment]
30-50% on iPhone SE 13.6. Seems to not repro in 14 though.

**Comment by ryango** [comment]
When it happens, it's always the second audio track added to the DOM. Using the JS quickstart code.

**Comment by ryango** [comment]
We do have a modification that gets local media at the same time as connecting - delaying recording start seems to help

**Comment by RusseII** [comment]
@anna-vasilko any more updates on the timeline? 13 days ago you said you were aiming for a release within the week. I'm assuming some unexpected things came up. Do you have an updated timeline? 

Asking again because this is a problem for a significant percentage of our user base and we have a few pilots paused while we wait for a fix.

**Comment by manjeshbhargav** [comment]
@RusseII ,

We just released [v2.6.0](https://github.com/twilio/twilio-video.js/releases/2.6.0), which contains workarounds for a couple of these issues. Please try it out and see if it improves the user experience on iOS Safari.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by anna-vasilko** [comment]
@RusseII Yes, as was mentioned above, the latest SDK release [v2.6.0](https://github.com/twilio/twilio-video.js/releases/2.6.0) contains the workaround for the issue #2 (audio can't be heard after interruptions by other apps like Siri, Youtube, Facetime etc). The workaround is expected to work on iOS versions 13.4.X and 13.5.x, and based on our testing it solves the problem in most of the interruption use cases.
We will continue adding iterative improvements in the future for some more rare/eddy use cases.

**Comment by XuanyuHu** [comment]
@anna-vasilko , could you confirm if the iOS/iPadOS 13.6 (13.5.5) has all the fix for issue #1 Remote audio does not play occasionally in iOS Safari browser?

I believe Apple renamed 13.5.5 to 13.6 and just want to get an offical confirmation from Twilio team about the fix is deployed with iOS 13.6

**Comment by XuanyuHu** [comment]
@anna-vasilko , after upgrading the iOS and iPadOS to 13.6, with the latest SDK: https://github.com/twilio/twilio-video.js/releases/tag/2.7.0 
We still see audio issues on iPhone and iPad devices.
Could you confirm if the Safari fix is patched in the 13.6 iOS/iPad release?

**Comment by anna-vasilko** [comment]
@XuanyuHu  Hi! Thanks for the info.
Issue #1 (Remote audio does not play occasionally) - is fixed by Apple since iOS 13.5.5 and the fix seems to be included in iOS 13.6. In our testing we can't reproduce this with iOS 13.6.

Issue #2 (Can't hear audio from iOS Safari after using another app) - This is still reproducible in some of the interruption use cases with iOS version 13.6 and 14 Beta. Our workaround works well in 13.4 and 13.5 but not as well in those newer versions and we are actively working on improving there. 
It is hard to say either you are hitting this interruption issue or something different. Could you please share a room sid and reproduction steps so we can investigate further? Opening a separate ticket would be preferable.

**Comment by XuanyuHu** [comment]
Thanks, @anna-vasilko .  We will keep testing on #1 and open a support ticket if we have any issues.

**Comment by webjay** [comment]
Sorry if this is the wrong place to ask, but how can I detect if a user can't hear or see a peer?

**Comment by manjeshbhargav** [comment]
Hi everyone,

We have just released version [2.7.1](https://github.com/twilio/twilio-video.js/releases/2.7.1) which has workarounds for several iOS Safari audio and video bugs. Our internal testing showed that most of the common iOS Safari issues have been worked around in this release. Please try it out and share any feedback you may have for us.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by TravBradfield** [comment]
@manjeshbhargav 

Thanks for this update! Do you still suggest implementing a "test mic" check before entering a call? 

I'm still having the same issues when calling between mac and iPadOS Safari. The way to solve the issue seems to be simple minimise safari and then reopen it then the audio works fine. 

Should I be doing the mic test before entering the call?

**Comment by manjeshbhargav** [comment]
@TravBradfield ,

Yes, I would recommend checking the microphone (and camera) before joining the Room. Our [best practices guide](https://www.twilio.com/docs/video/build-js-video-application-recommendations-and-best-practices#testing-the-microphone-and-camera) shows how you can build an audio level indicator. Hope it helps.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by TravBradfield** [comment]
@manjeshbhargav Thanks. 

Do you have any recommendations for auto playing audio policy on mobile browsers? I'm able to get the microphone and videos fine. Just the iPad/iPhone is not playing the sound from the video... I'm making sure that the video is only joined after the user interacts with the screen Still no audio playing on the Safari mobile device.

**Comment by manjeshbhargav** [comment]
@TravBradfield ,

Can you share Room SIDs and browser console logs (enable SDK logging by passing `logLevel: 'debug'` to `createLocalTracks()` and `connect()`.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by TravBradfield** [comment]
sid: RM0493997e3cebce408e0948cae4b57d80

2020-08-01 07:21:02.447Z | DEBUG in [connect #1]: Transport connected: Object
vendor-es2015.js:210217 2020-08-01 07:21:02.447Z | DEBUG in [PeerConnectionV2 #1: 5891947f-fad6-4b02-80dc-11b18e28c3ce]: Updated ICE reconnection timeout period: 30000
vendor-es2015.js:210217 2020-08-01 07:21:02.449Z | INFO in [LocalParticipant #1]: Added a new AudioTrackPublication: MT40e3076623d30384e5db72442897e5f5
vendor-es2015.js:210217 2020-08-01 07:21:02.449Z | DEBUG in [LocalParticipant #1]: AudioTrackPublication: LocalAudioTrackPublication
vendor-es2015.js:210217 2020-08-01 07:21:02.450Z | INFO in [LocalParticipant #1]: Added a new VideoTrackPublication: MT3c5f40f0656125269cd3186455e268e3
vendor-es2015.js:210217 2020-08-01 07:21:02.450Z | DEBUG in [LocalParticipant #1]: VideoTrackPublication: LocalVideoTrackPublication
2vendor-es2015.js:210217 2020-08-01 07:21:02.450Z | DEBUG in [LocalParticipant #1: PA3c5e16a93350d867576020c7f3945873]: Transitioned to state: connected
vendor-es2015.js:210217 2020-08-01 07:21:02.450Z | INFO in [LocalParticipant #1: PA3c5e16a93350d867576020c7f3945873]: reconnected
vendor-es2015.js:210217 2020-08-01 07:21:02.450Z | DEBUG in [connect #1]: Transport state changed: connected
vendor-es2015.js:210217 2020-08-01 07:21:02.451Z | DEBUG in [Room #1: RM0493997e3cebce408e0948cae4b57d80]: Creating a new RemoteParticipant for each ParticipantSignaling in the RoomSignaling
vendor-es2015.js:210217 2020-08-01 07:21:02.451Z | DEBUG in [Room #1: RM0493997e3cebce408e0948cae4b57d80]: Setting up RemoteParticipant creation for all subsequent ParticipantSignalings that connect to the RoomSignaling
vendor-es2015.js:210217 2020-08-01 07:21:02.451Z | INFO in [Room #1: RM0493997e3cebce408e0948cae4b57d80]: Created a new Room: IKEnkKICWmflst7c8Pky
vendor-es2015.js:210217 2020-08-01 07:21:02.451Z | DEBUG in [Room #1: RM0493997e3cebce408e0948cae4b57d80]: Initial RemoteParticipants: Array(0)
vendor-es2015.js:210217 2020-08-01 07:21:02.451Z | DEBUG in [connect #1]: Creating a new Room: Room
vendor-es2015.js:210217 2020-08-01 07:21:02.452Z | INFO in [connect #1]: Connected to Room: [Room #1: RM0493997e3cebce408e0948cae4b57d80]
vendor-es2015.js:210217 2020-08-01 07:21:02.452Z | INFO in [connect #1]: Room name: IKEnkKICWmflst7c8Pky
vendor-es2015.js:210217 2020-08-01 07:21:02.452Z | DEBUG in [connect #1]: Room: Room
main-es2015.js:1604 Connected to Room: IKEnkKICWmflst7c8Pky
main-es2015.js:1606 Successfully joined a Room: [Room #1: RM0493997e3cebce408e0948cae4b57d80]
vendor-es2015.js:210217 2020-08-01 07:21:02.452Z | DEBUG in [LocalVideoTrack #2: 4bc90d49-62a4-4634-8b9c-8e45dbe97d63]: Attempting to attach to element: <video autoplay playsinline>​</video>​
main-es2015.js:1625 ***** the one you looking for:  MediaStreamTrack
vendor-es2015.js:210217 2020-08-01 07:21:02.534Z | DEBUG in [TwilioConnection #1: wss://global.vss.twilio.com/signaling]: Incoming: {"body":{"version":2,"type":"update","sid":"RM0493997e3cebce408e0948cae4b57d80","name":"RM0493997e3cebce408e0948cae4b57d80","participant":{"sid":"PA3c5e16a93350d867576020c7f3945873","identity":"travis.bradfield1@gmail.com","tracks":[{"kind":"audio","priority":"standard","id":"dee4909e-af12-4f14-a532-c856c954c693","enabled":true,"sid":"MT40e3076623d30384e5db72442897e5f5","name":"74ca5ae9-1600-4368-8420-a897d89a1105","state":"ready"},{"kind":"video","priority":"standard","id":"990bb1de-342b-4791-8063-762670325161","enabled":true,"sid":"MT3c5f40f0656125269cd3186455e268e3","name":"4bc90d49-62a4-4634-8b9c-8e45dbe97d63","state":"ready"}],"revision":3,"state":"connected"},"participants":[],"recording":{"enabled":false,"revision":1},"subscribe":{"revision":1,"rules":[{"type":"include","all":true}]},"subscribed":{"revision":1,"tracks":[]},"published":{"revision":3,"tracks":[{"kind":"audio","priority":"standard","id":"dee4909e-af12-4f14-a532-c856c954c693","enabled":true,"sid":"MT40e3076623d30384e5db72442897e5f5","name":"74ca5ae9-1600-4368-8420-a897d89a1105","state":"ready"},{"kind":"video","priority":"standard","id":"990bb1de-342b-4791-8063-762670325161","enabled":true,"sid":"MT3c5f40f0656125269cd3186455e268e3","name":"4bc90d49-62a4-4634-8b9c-8e45dbe97d63","state":"ready"}]}},"type":"msg"}
vendor-es2015.js:210217 2020-08-01 07:21:02.536Z | DEBUG in [TwilioConnection #1: wss://global.vss.twilio.com/signaling]: Incoming: {"body":{"version":2,"type":"update","peer_connections":[{"id":"5891947f-fad6-4b02-80dc-11b18e28c3ce","description":{"type":"close","revision":3}}],"sid":"RM0493997e3cebce408e0948cae4b57d80","name":"RM0493997e3cebce408e0948cae4b57d80","participant":{"sid":"PA3c5e16a93350d867576020c7f3945873","identity":"travis.bradfield1@gmail.com","tracks":[{"kind":"audio","priority":"standard","id":"dee4909e-af12-4f14-a532-c856c954c693","enabled":true,"sid":"MT40e3076623d30384e5db72442897e5f5","name":"74ca5ae9-1600-4368-8420-a897d89a1105","state":"ready"},{"kind":"video","priority":"standard","id":"990bb1de-342b-4791-8063-762670325161","enabled":true,"sid":"MT3c5f40f0656125269cd3186455e268e3","name":"4bc90d49-62a4-4634-8b9c-8e45dbe97d63","state":"ready"}],"revision":3,"state":"connected"},"participants":[],"recording":{"enabled":false,"revision":1},"subscribe":{"revision":1,"rules":[{"type":"include","all":true}]},"subscribed":{"revision":1,"tracks":[]},"published":{"revision":3,"tracks":[{"kind":"audio","priority":"standard","id":"dee4909e-af12-4f14-a532-c856c954c693","enabled":true,"sid":"MT40e3076623d30384e5db72442897e5f5","name":"74ca5ae9-1600-4368-8420-a897d89a1105","state":"ready"},{"kind":"video","priority":"standard","id":"990bb1de-342b-4791-8063-762670325161","enabled":true,"sid":"MT3c5f40f0656125269cd3186455e268e3","name":"4bc90d49-62a4-4634-8b9c-8e45dbe97d63","state":"ready"}]}},"type":"msg"}
vendor-es2015.js:210217 2020-08-01 07:21:03.426Z | DEBUG in [LocalVideoTrack #2: 4bc90d49-62a4-4634-8b9c-8e45dbe97d63]: Dimensions: Object
vendor-es2015.js:210217 2020-08-01 07:21:03.427Z | DEBUG in [LocalVideoTrack #2: 4bc90d49-62a4-4634-8b9c-8e45dbe97d63]: Started
vendor-es2015.js:210217 2020-08-01 07:21:06.471Z | DEBUG in [TwilioConnection #1: wss://global.vss.twilio.com/signaling]: Incoming: {"type":"heartbeat"}
vendor-es2015.js:210217 2020-08-01 07:21:07.025Z | DEBUG in [TwilioConnection #1: wss://global.vss.twilio.com/signaling]: Outgoing: {"type":"heartbeat"}
vendor-es2015.js:210217 2020-08-01 07:21:10.981Z | DEBUG in [TwilioConnection #1: wss://global.vss.twilio.com/signaling]: Incoming: {"type":"heartbeat"}
vendor-es2015.js:210217 2020-08-01 07:21:11.826Z | DEBUG in [TwilioConnection #1: wss://global.vss.twilio.com/signaling]: Outgoing: {"type":"heartbeat"}
vendor-es2015.js:210217 2020-08-01 07:21:15.582Z | DEBUG in [TwilioConnection #1: wss://global.vss.twilio.com/signaling]: Incoming: {"type":"heartbeat"}
vendor-es2015.js:210217 2020-08-01 07:21:16.626Z | DEBUG in [TwilioConnection #1: wss://global.vss.twilio.com/signaling]: Outgoing: {"type":"heartbeat"}
vendor-es2015.js:210217 2020-08-01 07:21:20.180Z | DEBUG in [TwilioConnection #1: wss://global.vss.twilio.com/signaling]: Incoming: {"type":"heartbeat"}
vendor-es2015.js:210217 2020-08-01 07:21:21.426Z | DEBUG in [TwilioConnection #1: wss://global.vss.twilio.com/signaling]: Outgoing: {"type":"heartbeat"}
vendor-es2015.js:210217 2020-08-01 07:21:24.781Z | DEBUG in [TwilioConnection #1: wss://global.vss.twilio.com/signaling]: Incoming: {"type":"heartbeat"}
vendor-es2015.js:210217 2020-08-01 07:21:26.227Z | DEBUG in [TwilioConnection #1: wss://global.vss.twilio.com/signaling]: Outgoing: {"type":"heartbeat"}
vendor-es2015.js:210217 2020-08-01 07:21:29.380Z | DEBUG in [TwilioConnection #1: wss://global.vss.twilio.com/signaling]: Incoming: {"type":"heartbeat"}
vendor-es2015.js:210217 2020-08-01 07:21:31.027Z | DEBUG in [TwilioConnection #1: wss://global.vss.twilio.com/signaling]: Outgoing: {"type":"heartbeat"}
vendor-es2015.js:210217 2020-08-01 07:21:33.980Z | DEBUG in [TwilioConnection #1: wss://global.vss.twilio.com/signaling]: Incoming: {"type":"heartbeat"}
vendor-es2015.js:210217 2020-08-01 07:21:35.828Z | DEBUG in [TwilioConnection #1: wss://global.vss.twilio.com/signaling]: Outgoing: {"type":"heartbeat"}
vendor-es2015.js:210217 2020-08-01 07:21:38.522Z | DEBUG in [TwilioConnection #1: wss://global.vss.twilio.com/signaling]: Incoming: {"type":"heartbeat"}
vendor-es2015.js:210217 2020-08-01 07:21:40.629Z | DEBUG in [TwilioConnection #1: wss://global.vss.twilio.com/signaling]: Outgoing: {"type":"heartbeat"}
vendor-es2015.js:210217 2020-08-01 07:21:43.080Z | DEBUG in [TwilioConnection #1: wss://global.vss.twilio.com/signaling]: Incoming: {"type":"heartbeat"}
vendor-es2015.js:210217 2020-08-01 07:21:45.430Z | DEBUG in [TwilioConnection #1: wss://global.vss.twilio.com/signaling]: Outgoing: {"type":"heartbeat"}
vendor-es2015.js:210217 2020-08-01 07:21:47.636Z | DEBUG in [TwilioConnection #1: wss://global.vss.twilio.com/signaling]: Incoming: {"type":"heartbeat"}
vendor-es2015.js:210217 2020-08-01 07:21:49.111Z | DEBUG in [TwilioConnection #1: wss://global.vss.twilio.com/signaling]: Incoming: {"body":{"version":2,"type":"update","sid":"RM0493997e3cebce408e0948cae4b57d80","name":"RM0493997e3cebce408e0948cae4b57d80","participant":{"sid":"PA3c5e16a93350d867576020c7f3945873","identity":"travis.bradfield1@gmail.com","tracks":[{"kind":"audio","priority":"standard","id":"dee4909e-af12-4f14-a532-c856c954c693","enabled":true,"sid":"MT40e3076623d30384e5db72442897e5f5","name":"74ca5ae9-1600-4368-8420-a897d89a1105","state":"ready"},{"kind":"video","priority":"standard","id":"990bb1de-342b-4791-8063-762670325161","enabled":true,"sid":"MT3c5f40f0656125269cd3186455e268e3","name":"4bc90d49-62a4-4634-8b9c-8e45dbe97d63","state":"ready"}],"revision":3,"state":"connected"},"participants":[{"sid":"PA29e19078f7e310f8c080dfa2f5bf205b","identity":"anonymousRecipient","tracks":[{"kind":"video","priority":"standard","id":"a6755d26-ce9f-4370-80b7-5428ad65024e","enabled":true,"sid":"MT5fdb4240de58435969d92427d15929c3","name":"f5648ad7-dc4f-4e25-abc6-8e73a7370107","state":"ready"},{"kind":"audio","priority":"standard","id":"2f85deff-aec7-4998-99f0-5ce2cb12783a","enabled":true,"sid":"MT454a2650bcffe26a9eefc6f5181f5a63","name":"1072c97a-59ac-4c97-965f-4d3bdc87b253","state":"ready"}],"revision":3,"state":"connected"}],"recording":{"enabled":false,"revision":1},"subscribe":{"revision":1,"rules":[{"type":"include","all":true}]},"subscribed":{"revision":2,"tracks":[{"id":"2f85deff-aec7-4998-99f0-5ce2cb12783a","sid":"MT454a2650bcffe26a9eefc6f5181f5a63"},{"id":"a6755d26-ce9f-4370-80b7-5428ad65024e","sid":"MT5fdb4240de58435969d92427d15929c3"}]},"published":{"revision":3,"tracks":[{"kind":"audio","priority":"standard","id":"dee4909e-af12-4f14-a532-c856c954c693","enabled":true,"sid":"MT40e3076623d30384e5db72442897e5f5","name":"74ca5ae9-1600-4368-8420-a897d89a1105","state":"ready"},{"kind":"video","priority":"standard","id":"990bb1de-342b-4791-8063-762670325161","enabled":true,"sid":"MT3c5f40f0656125269cd3186455e268e3","name":"4bc90d49-62a4-4634-8b9c-8e45dbe97d63","state":"ready"}]}},"type":"msg"}
vendor-es2015.js:210217 2020-08-01 07:21:49.112Z | INFO in [RemoteParticipant #2: PA29e19078f7e310f8c080dfa2f5bf205b]: Created a new Participant: anonymousRecipient
vendor-es2015.js:210217 2020-08-01 07:21:49.113Z | INFO in [RemoteParticipant #2: PA29e19078f7e310f8c080dfa2f5bf205b]: Added a new VideoTrackPublication: MT5fdb4240de58435969d92427d15929c3
vendor-es2015.js:210217 2020-08-01 07:21:49.113Z | DEBUG in [RemoteParticipant #2: PA29e19078f7e310f8c080dfa2f5bf205b]: VideoTrackPublication: RemoteVideoTrackPublication
vendor-es2015.js:210217 2020-08-01 07:21:49.113Z | INFO in [RemoteParticipant #2: PA29e19078f7e310f8c080dfa2f5bf205b]: Added a new AudioTrackPublication: MT454a2650bcffe26a9eefc6f5181f5a63
vendor-es2015.js:210217 2020-08-01 07:21:49.113Z | DEBUG in [RemoteParticipant #2: PA29e19078f7e310f8c080dfa2f5bf205b]: AudioTrackPublication: RemoteAudioTrackPublication
vendor-es2015.js:210217 2020-08-01 07:21:49.113Z | INFO in [Room #1: RM0493997e3cebce408e0948cae4b57d80]: A new RemoteParticipant connected: RemoteParticipant
main-es2015.js:1559 Participant "anonymousRecipient" connected
main-es2015.js:1573 OVER HERE
main-es2015.js:1613 A remote Participant connected: [RemoteParticipant #2: PA29e19078f7e310f8c080dfa2f5bf205b]
vendor-es2015.js:210217 2020-08-01 07:21:49.116Z | DEBUG in [TwilioConnection #1: wss://global.vss.twilio.com/signaling]: Incoming: {"body":{"version":2,"type":"update","peer_connections":[{"id":"77d99c80-ab07-4458-8333-594499a9c60f","description":{"type":"offer","sdp":"v=0\r\no=- 2752126399633827172 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:BUNDLE 0 1\r\na=msid-semantic: WMS\r\nm=audio 9 UDP/TLS/RTP/SAVPF 111 103 9 102 0 8 105 13 110 113 126\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:CPGh\r\na=ice-pwd:vjuFXyrZN0eEzQwX6kM4Vkyv\r\na=ice-options:trickle\r\na=fingerprint:sha-256 AB:C3:61:53:01:C7:06:05:B9:71:65:DC:4D:A3:E3:F7:B1:F6:6A:75:E2:20:7C:92:8D:B8:30:BD:5F:BD:EC:37\r\na=setup:actpass\r\na=mid:0\r\na=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level\r\na=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01\r\na=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid\r\na=extmap:5 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id\r\na=extmap:6 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id\r\na=sendrecv\r\na=msid:- 2f85deff-aec7-4998-99f0-5ce2cb12783a\r\na=rtcp-mux\r\na=rtpmap:111 opus/48000/2\r\na=rtcp-fb:111 transport-cc\r\na=fmtp:111 minptime=10;useinbandfec=1\r\na=rtpmap:103 ISAC/16000\r\na=rtpmap:9 G722/8000\r\na=rtpmap:102 ILBC/8000\r\na=rtpmap:0 PCMU/8000\r\na=rtpmap:8 PCMA/8000\r\na=rtpmap:105 CN/16000\r\na=rtpmap:13 CN/8000\r\na=rtpmap:110 telephone-event/48000\r\na=rtpmap:113 telephone-event/16000\r\na=rtpmap:126 telephone-event/8000\r\na=ssrc:327153391 cname:83hPDYbINc3jzCTv\r\na=ssrc:327153391 msid:- 2f85deff-aec7-4998-99f0-5ce2cb12783a\r\nm=video 9 UDP/TLS/RTP/SAVPF 96 98 97 99 101 125 100 127 104\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:CPGh\r\na=ice-pwd:vjuFXyrZN0eEzQwX6kM4Vkyv\r\na=ice-options:trickle\r\na=fingerprint:sha-256 AB:C3:61:53:01:C7:06:05:B9:71:65:DC:4D:A3:E3:F7:B1:F6:6A:75:E2:20:7C:92:8D:B8:30:BD:5F:BD:EC:37\r\na=setup:actpass\r\na=mid:1\r\na=extmap:14 urn:ietf:params:rtp-hdrext:toffset\r\na=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=extmap:13 urn:3gpp:video-orientation\r\na=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01\r\na=extmap:12 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay\r\na=extmap:11 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type\r\na=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing\r\na=extmap:8 http://tools.ietf.org/html/draft-ietf-avtext-framemarking-07\r\na=extmap:9 http://www.webrtc.org/experiments/rtp-hdrext/color-space\r\na=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid\r\na=extmap:5 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id\r\na=extmap:6 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id\r\na=sendrecv\r\na=msid:- a6755d26-ce9f-4370-80b7-5428ad65024e\r\na=rtcp-mux\r\na=rtcp-rsize\r\na=rtpmap:96 H264/90000\r\na=rtcp-fb:96 goog-remb\r\na=rtcp-fb:96 transport-cc\r\na=rtcp-fb:96 ccm fir\r\na=rtcp-fb:96 nack\r\na=rtcp-fb:96 nack pli\r\na=fmtp:96 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=640c1f\r\na=rtpmap:97 rtx/90000\r\na=fmtp:97 apt=96\r\na=rtpmap:98 H264/90000\r\na=rtcp-fb:98 goog-remb\r\na=rtcp-fb:98 transport-cc\r\na=rtcp-fb:98 ccm fir\r\na=rtcp-fb:98 nack\r\na=rtcp-fb:98 nack pli\r\na=fmtp:98 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f\r\na=rtpmap:99 rtx/90000\r\na=fmtp:99 apt=98\r\na=rtpmap:100 VP8/90000\r\na=rtcp-fb:100 goog-remb\r\na=rtcp-fb:100 transport-cc\r\na=rtcp-fb:100 ccm fir\r\na=rtcp-fb:100 nack\r\na=rtcp-fb:100 nack pli\r\na=rtpmap:101 rtx/90000\r\na=fmtp:101 apt=100\r\na=rtpmap:127 red/90000\r\na=rtpmap:125 rtx/90000\r\na=fmtp:125 apt=127\r\na=rtpmap:104 ulpfec/90000\r\na=ssrc-group:FID 178180768 3114830086\r\na=ssrc:178180768 cname:83hPDYbINc3jzCTv\r\na=ssrc:178180768 msid:- a6755d26-ce9f-4370-80b7-5428ad65024e\r\na=ssrc:3114830086 cname:83hPDYbINc3jzCTv\r\na=ssrc:3114830086 msid:- a6755d26-ce9f-4370-80b7-5428ad65024e\r\n","revision":1}}],"sid":"RM0493997e3cebce408e0948cae4b57d80","name":"RM0493997e3cebce408e0948cae4b57d80","participant":{"sid":"PA3c5e16a93350d867576020c7f3945873","identity":"travis.bradfield1@gmail.com","tracks":[{"kind":"audio","priority":"standard","id":"dee4909e-af12-4f14-a532-c856c954c693","enabled":true,"sid":"MT40e3076623d30384e5db72442897e5f5","name":"74ca5ae9-1600-4368-8420-a897d89a1105","state":"ready"},{"kind":"video","priority":"standard","id":"990bb1de-342b-4791-8063-762670325161","enabled":true,"sid":"MT3c5f40f0656125269cd3186455e268e3","name":"4bc90d49-62a4-4634-8b9c-8e45dbe97d63","state":"ready"}],"revision":3,"state":"connected"},"participants":[{"sid":"PA29e19078f7e310f8c080dfa2f5bf205b","identity":"anonymousRecipient","tracks":[{"kind":"video","priority":"standard","id":"a6755d26-ce9f-4370-80b7-5428ad65024e","enabled":true,"sid":"MT5fdb4240de58435969d92427d15929c3","name":"f5648ad7-dc4f-4e25-abc6-8e73a7370107","state":"ready"},{"kind":"audio","priority":"standard","id":"2f85deff-aec7-4998-99f0-5ce2cb12783a","enabled":true,"sid":"MT454a2650bcffe26a9eefc6f5181f5a63","name":"1072c97a-59ac-4c97-965f-4d3bdc87b253","state":"ready"}],"revision":3,"state":"connected"}],"recording":{"enabled":false,"revision":1},"subscribe":{"revision":1,"rules":[{"type":"include","all":true}]},"subscribed":{"revision":2,"tracks":[{"id":"2f85deff-aec7-4998-99f0-5ce2cb12783a","sid":"MT454a2650bcffe26a9eefc6f5181f5a63"},{"id":"a6755d26-ce9f-4370-80b7-5428ad65024e","sid":"MT5fdb4240de58435969d92427d15929c3"}]},"published":{"revision":3,"tracks":[{"kind":"audio","priority":"standard","id":"dee4909e-af12-4f14-a532-c856c954c693","enabled":true,"sid":"MT40e3076623d30384e5db72442897e5f5","name":"74ca5ae9-1600-4368-8420-a897d89a1105","state":"ready"},{"kind":"video","priority":"standard","id":"990bb1de-342b-4791-8063-762670325161","enabled":true,"sid":"MT3c5f40f0656125269cd3186455e268e3","name":"4bc90d49-62a4-4634-8b9c-8e45dbe97d63","state":"ready"}]}},"type":"msg"}
vendor-es2015.js:210217 2020-08-01 07:21:49.127Z | DEBUG in [RemoteAudioTrack #4: undefined]: Initializing
vendor-es2015.js:210217 2020-08-01 07:21:49.127Z | INFO in [RemoteParticipant #2: PA29e19078f7e310f8c080dfa2f5bf205b]: Added a new AudioTrack: 2f85deff-aec7-4998-99f0-5ce2cb12783a
vendor-es2015.js:210217 2020-08-01 07:21:49.127Z | DEBUG in [RemoteParticipant #2: PA29e19078f7e310f8c080dfa2f5bf205b]: AudioTrack: RemoteAudioTrack
main-es2015.js:1551 track subscribed:  RemoteAudioTrack
vendor-es2015.js:210217 2020-08-01 07:21:49.127Z | DEBUG in [RemoteAudioTrack #4: MT454a2650bcffe26a9eefc6f5181f5a63]: Attempting to attach to element: <audio autoplay>​</audio>​
vendor-es2015.js:210217 2020-08-01 07:21:49.128Z | DEBUG in [RemoteVideoTrack #5: undefined]: Initializing
vendor-es2015.js:210217 2020-08-01 07:21:49.129Z | INFO in [RemoteParticipant #2: PA29e19078f7e310f8c080dfa2f5bf205b]: Added a new VideoTrack: a6755d26-ce9f-4370-80b7-5428ad65024e
vendor-es2015.js:210217 2020-08-01 07:21:49.129Z | DEBUG in [RemoteParticipant #2: PA29e19078f7e310f8c080dfa2f5bf205b]: VideoTrack: RemoteVideoTrack
main-es2015.js:1551 track subscribed:  RemoteVideoTrack
vendor-es2015.js:210217 2020-08-01 07:21:49.129Z | DEBUG in [RemoteVideoTrack #5: MT5fdb4240de58435969d92427d15929c3]: Attempting to attach to element: <video autoplay playsinline>​</video>​
vendor-es2015.js:210217 2020-08-01 07:21:49.133Z | DEBUG in [RemoteAudioTrack #4: MT454a2650bcffe26a9eefc6f5181f5a63]: Started
vendor-es2015.js:210217 2020-08-01 07:21:49.139Z | DEBUG in [TwilioConnection #1: wss://global.vss.twilio.com/signaling]: Outgoing: {"body":{"session":"a1d9506555c76a1ade723a17d7c018bc0493997e3cebce408e0948cae4b57d803c5e16a93350d867576020c7f3945873d729955f294d3f12f9df26914332fc19","type":"update","version":2,"peer_connections":[{"description":{"type":"answer","revision":1,"sdp":"v=0\r\no=- 8409046777413629192 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:BUNDLE 0 1\r\na=msid-semantic: WMS\r\nm=audio 9 UDP/TLS/RTP/SAVPF 111 103 9 0 8 105 13 110 113 126\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:7bpY\r\na=ice-pwd:NkFsaEdIoC94Q/FqCj4WArSq\r\na=ice-options:trickle\r\na=fingerprint:sha-256 9C:89:8D:43:C1:19:FE:ED:6A:02:C1:3D:68:7F:E2:0D:DE:90:20:10:12:6A:67:34:6F:49:C0:B3:BA:67:BF:09\r\na=setup:active\r\na=mid:0\r\na=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level\r\na=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01\r\na=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid\r\na=extmap:5 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id\r\na=extmap:6 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id\r\na=recvonly\r\na=rtcp-mux\r\na=rtpmap:111 opus/48000/2\r\na=rtcp-fb:111 transport-cc\r\na=fmtp:111 minptime=10;useinbandfec=1\r\na=rtpmap:103 ISAC/16000\r\na=rtpmap:9 G722/8000\r\na=rtpmap:0 PCMU/8000\r\na=rtpmap:8 PCMA/8000\r\na=rtpmap:105 CN/16000\r\na=rtpmap:13 CN/8000\r\na=rtpmap:110 telephone-event/48000\r\na=rtpmap:113 telephone-event/16000\r\na=rtpmap:126 telephone-event/8000\r\nm=video 9 UDP/TLS/RTP/SAVPF 98 99 101 125 100 127 104\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:7bpY\r\na=ice-pwd:NkFsaEdIoC94Q/FqCj4WArSq\r\na=ice-options:trickle\r\na=fingerprint:sha-256 9C:89:8D:43:C1:19:FE:ED:6A:02:C1:3D:68:7F:E2:0D:DE:90:20:10:12:6A:67:34:6F:49:C0:B3:BA:67:BF:09\r\na=setup:active\r\na=mid:1\r\na=extmap:14 urn:ietf:params:rtp-hdrext:toffset\r\na=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=extmap:13 urn:3gpp:video-orientation\r\na=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01\r\na=extmap:12 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay\r\na=extmap:11 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type\r\na=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing\r\na=extmap:8 http://tools.ietf.org/html/draft-ietf-avtext-framemarking-07\r\na=extmap:9 http://www.webrtc.org/experiments/rtp-hdrext/color-space\r\na=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid\r\na=extmap:5 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id\r\na=extmap:6 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id\r\na=recvonly\r\na=rtcp-mux\r\na=rtcp-rsize\r\na=rtpmap:98 H264/90000\r\na=rtcp-fb:98 goog-remb\r\na=rtcp-fb:98 transport-cc\r\na=rtcp-fb:98 ccm fir\r\na=rtcp-fb:98 nack\r\na=rtcp-fb:98 nack pli\r\na=fmtp:98 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f\r\na=rtpmap:99 rtx/90000\r\na=fmtp:99 apt=98\r\na=rtpmap:101 rtx/90000\r\na=fmtp:101 apt=100\r\na=rtpmap:125 rtx/90000\r\na=fmtp:125 apt=127\r\na=rtpmap:100 VP8/90000\r\na=rtcp-fb:100 goog-remb\r\na=rtcp-fb:100 transport-cc\r\na=rtcp-fb:100 ccm fir\r\na=rtcp-fb:100 nack\r\na=rtcp-fb:100 nack pli\r\na=rtpmap:127 red/90000\r\na=rtpmap:104 ulpfec/90000\r\n"},"id":"77d99c80-ab07-4458-8333-594499a9c60f"}],"participant":{"revision":3,"tracks":[{"enabled":true,"id":"dee4909e-af12-4f14-a532-c856c954c693","kind":"audio","name":"74ca5ae9-1600-4368-8420-a897d89a1105","priority":"standard"},{"enabled":true,"id":"990bb1de-342b-4791-8063-762670325161","kind":"video","name":"4bc90d49-62a4-4634-8b9c-8e45dbe97d63","priority":"standard"}]}},"type":"msg"}
vendor-es2015.js:210217 2020-08-01 07:21:49.147Z | DEBUG in [TwilioConnection #1: wss://global.vss.twilio.com/signaling]: Outgoing: {"body":{"session":"a1d9506555c76a1ade723a17d7c018bc0493997e3cebce408e0948cae4b57d803c5e16a93350d867576020c7f3945873d729955f294d3f12f9df26914332fc19","type":"update","version":2,"peer_connections":[{"description":{"type":"offer","revision":2,"sdp":"v=0\r\no=- 8409046777413629192 3 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:BUNDLE 0 1 2 3\r\na=msid-semantic: WMS\r\nm=audio 52776 UDP/TLS/RTP/SAVPF 111 103 124 9 0 8 105 13 106 110 113 126 112\r\nc=IN IP4 192.168.0.70\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=candidate:3127768281 1 udp 2122262783 2a02:c7d:e043:c200:4dbf:f2fd:d821:4a38 51152 typ host generation 0 network-id 2 network-cost 10\r\na=candidate:3661447420 1 udp 2122194687 192.168.0.70 52776 typ host generation 0 network-id 1 network-cost 10\r\na=ice-ufrag:7bpY\r\na=ice-pwd:NkFsaEdIoC94Q/FqCj4WArSq\r\na=ice-options:trickle\r\na=fingerprint:sha-256 9C:89:8D:43:C1:19:FE:ED:6A:02:C1:3D:68:7F:E2:0D:DE:90:20:10:12:6A:67:34:6F:49:C0:B3:BA:67:BF:09\r\na=setup:actpass\r\na=mid:0\r\na=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level\r\na=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01\r\na=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid\r\na=extmap:5 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id\r\na=extmap:6 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id\r\na=recvonly\r\na=rtcp-mux\r\na=rtpmap:111 opus/48000/2\r\na=rtcp-fb:111 transport-cc\r\na=fmtp:111 minptime=10;useinbandfec=1\r\na=rtpmap:103 ISAC/16000\r\na=rtpmap:9 G722/8000\r\na=rtpmap:0 PCMU/8000\r\na=rtpmap:8 PCMA/8000\r\na=rtpmap:105 CN/16000\r\na=rtpmap:13 CN/8000\r\na=rtpmap:110 telephone-event/48000\r\na=rtpmap:113 telephone-event/16000\r\na=rtpmap:126 telephone-event/8000\r\na=rtpmap:124 ISAC/32000\r\na=rtpmap:106 CN/32000\r\na=rtpmap:112 telephone-event/32000\r\nm=video 9 UDP/TLS/RTP/SAVPF 98 102 121 108 120 119 99 101 125 116 115 109 114 107 100 127 104\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:7bpY\r\na=ice-pwd:NkFsaEdIoC94Q/FqCj4WArSq\r\na=ice-options:trickle\r\na=fingerprint:sha-256 9C:89:8D:43:C1:19:FE:ED:6A:02:C1:3D:68:7F:E2:0D:DE:90:20:10:12:6A:67:34:6F:49:C0:B3:BA:67:BF:09\r\na=setup:actpass\r\na=mid:1\r\na=extmap:14 urn:ietf:params:rtp-hdrext:toffset\r\na=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=extmap:13 urn:3gpp:video-orientation\r\na=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01\r\na=extmap:12 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay\r\na=extmap:11 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type\r\na=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing\r\na=extmap:8 http://tools.ietf.org/html/draft-ietf-avtext-framemarking-07\r\na=extmap:9 http://www.webrtc.org/experiments/rtp-hdrext/color-space\r\na=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid\r\na=extmap:5 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id\r\na=extmap:6 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id\r\na=recvonly\r\na=rtcp-mux\r\na=rtcp-rsize\r\na=rtpmap:98 H264/90000\r\na=rtcp-fb:98 goog-remb\r\na=rtcp-fb:98 transport-cc\r\na=rtcp-fb:98 ccm fir\r\na=rtcp-fb:98 nack\r\na=rtcp-fb:98 nack pli\r\na=fmtp:98 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f\r\na=rtpmap:99 rtx/90000\r\na=fmtp:99 apt=98\r\na=rtpmap:101 rtx/90000\r\na=fmtp:101 apt=100\r\na=rtpmap:125 rtx/90000\r\na=fmtp:125 apt=127\r\na=rtpmap:100 VP8/90000\r\na=rtcp-fb:100 goog-remb\r\na=rtcp-fb:100 transport-cc\r\na=rtcp-fb:100 ccm fir\r\na=rtcp-fb:100 nack\r\na=rtcp-fb:100 nack pli\r\na=rtpmap:127 red/90000\r\na=rtpmap:104 ulpfec/90000\r\na=rtpmap:102 H264/90000\r\na=rtcp-fb:102 goog-remb\r\na=rtcp-fb:102 transport-cc\r\na=rtcp-fb:102 ccm fir\r\na=rtcp-fb:102 nack\r\na=rtcp-fb:102 nack pli\r\na=fmtp:102 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f\r\na=rtpmap:116 rtx/90000\r\na=fmtp:116 apt=102\r\na=rtpmap:121 H264/90000\r\na=rtcp-fb:121 goog-remb\r\na=rtcp-fb:121 transport-cc\r\na=rtcp-fb:121 ccm fir\r\na=rtcp-fb:121 nack\r\na=rtcp-fb:121 nack pli\r\na=fmtp:121 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42001f\r\na=rtpmap:115 rtx/90000\r\na=fmtp:115 apt=121\r\na=rtpmap:108 H264/90000\r\na=rtcp-fb:108 goog-remb\r\na=rtcp-fb:108 transport-cc\r\na=rtcp-fb:108 ccm fir\r\na=rtcp-fb:108 nack\r\na=rtcp-fb:108 nack pli\r\na=fmtp:108 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42e01f\r\na=rtpmap:109 rtx/90000\r\na=fmtp:109 apt=108\r\na=rtpmap:120 H264/90000\r\na=rtcp-fb:120 goog-remb\r\na=rtcp-fb:120 transport-cc\r\na=rtcp-fb:120 ccm fir\r\na=rtcp-fb:120 nack\r\na=rtcp-fb:120 nack pli\r\na=fmtp:120 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=4d0032\r\na=rtpmap:114 rtx/90000\r\na=fmtp:114 apt=120\r\na=rtpmap:119 H264/90000\r\na=rtcp-fb:119 goog-remb\r\na=rtcp-fb:119 transport-cc\r\na=rtcp-fb:119 ccm fir\r\na=rtcp-fb:119 nack\r\na=rtcp-fb:119 nack pli\r\
vendor-es2015.js:210217 2020-08-01 07:21:49.147Z | DEBUG in [PeerConnectionV2 #2: 77d99c80-ab07-4458-8333-594499a9c60f]: ICE gathering state is "gathering"
vendor-es2015.js:210217 2020-08-01 07:21:49.148Z | DEBUG in [PeerConnectionV2 #2: 77d99c80-ab07-4458-8333-594499a9c60f]: Starting ICE gathering timeout: 15000
vendor-es2015.js:210217 2020-08-01 07:21:49.148Z | DEBUG in [PeerConnectionV2 #2: 77d99c80-ab07-4458-8333-594499a9c60f]: Clearing ICE gathering timeout
vendor-es2015.js:210217 2020-08-01 07:21:49.148Z | DEBUG in [TwilioConnection #1: wss://global.vss.twilio.com/signaling]: Outgoing: {"body":{"session":"a1d9506555c76a1ade723a17d7c018bc0493997e3cebce408e0948cae4b57d803c5e16a93350d867576020c7f3945873d729955f294d3f12f9df26914332fc19","type":"update","version":2,"peer_connections":[{"ice":{"candidates":[{"candidate":"candidate:3127768281 1 udp 2122262783 2a02:c7d:e043:c200:4dbf:f2fd:d821:4a38 51152 typ host generation 0 ufrag 7bpY network-id 2 network-cost 10","sdpMid":"0","sdpMLineIndex":0}],"ufrag":"7bpY","revision":1},"id":"77d99c80-ab07-4458-8333-594499a9c60f"}],"participant":{"revision":3,"tracks":[{"enabled":true,"id":"dee4909e-af12-4f14-a532-c856c954c693","kind":"audio","name":"74ca5ae9-1600-4368-8420-a897d89a1105","priority":"standard"},{"enabled":true,"id":"990bb1de-342b-4791-8063-762670325161","kind":"video","name":"4bc90d49-62a4-4634-8b9c-8e45dbe97d63","priority":"standard"}]}},"type":"msg"}

**Comment by TravBradfield** [comment]
@manjeshbhargav There is a lot of log content, apologies if I have pasted a load of nonsense in here..

**Comment by dan-steno** [comment]
@anna-vasilko For issue #1 - we had a user who reported that they were only able to hear some of the remote participant's audio, but not all of them. For those who experienced issue #1 - was it an all or nothing thing? I'm trying to figure out if this is related or not (I can't reproduce myself, but I'm on iOS 13.6 and this user was on 13.4.1).

**Comment by anna-vasilko** [comment]
@dan-steno It was not all or nothing, only some of the remote audio tracks would not play. Basically from what you describe it does sound like #1 issue, which is fixed in the latest iOS versions but could still happen in older ones.

**Comment by davidfritsche17** [comment]
Hello all.  I think this problem may be reoccurring in ios/iPadOS 13.7

Our WebRTC system had this issue with ios 13.5 and lower.  We confirmed it was fixed in ios 13.6 beta and the release on July 15th.  Since then we have not experienced this issue unless the device was not upgraded...until...

Yesterday, iOS 13.7 was released and immediately we had the problem again.  In our case it is a Webrtc Meeting platform and not all users can here the iPad user on the new iOS.

We are working to confirm this - can anyone else confirm this bug is now "unfixed" ?

Thanks.

**Comment by voigtd** [comment]
I can confirm that this is still a huge issue. Audio and video are not working at all on some mobile devices while working on others. I've tested with multiple different iPhones on different browsers and haven't been able to see a clear pattern of what is causing the issue. Based on the docs I've read from Twilio, they are not sure as well, or they just haven't had the time to make the fixes needed for audio and video on mobile browsers to work properly / consistently.

**Comment by voigtd** [comment]
I can confirm that this is still an issue.

Audio and video tracks are not working at all on some mobile devices while working on others. I've tested with multiple different iPhones on different browsers and haven't been able to see a clear pattern of what is causing the issue. It might be an issue with the iOS version - i.e. anything less than iOS 14 doesn't work, and 14+ does work - but I can't confirm.

Based on the docs I've read from Twilio, they are not sure what the cause is as well, or they just haven't had the time to make the fixes needed for audio and video to work properly / consistently on mobile browsers. I'd like more clarity.

**Comment by davidfritsche17** [comment]
voig, we had to redo our sdk to make this work.  Problem will still be there with iOS 13.6 and below.  It started happening on 13.7 as well, until we updated.  I hope that helps.

**Comment by voigtd** [comment]
@davidfritsche17 Thanks for the info. In general that makes sense since iOS 14 was working when I tested. However, I tested today on 13.7 and it wasn't working at all for `twilio-video` v2.7.1. I'll update to v2.7.2 and see what happens when testing with iOS 13.7. 

Also is this iOS compatibility documented anywhere?

**Comment by voigtd** [comment]
Tested again with Safari on two iPhones that are both using iOS 14 and the latest twilio-video sdk version and neither the audio or video is working properly. This issue definitely goes further than just iOS version incompatibility.

**Comment by anna-vasilko** [comment]
Hey @voigtd This ticket tracks very specific audio issues related to older versions of Safari, which were confirmed to be fixed in iOS14.
It sounds like you may experience something different, possibly specific to your application. Can you please open a separate ticket with detailed description of your impacted scenario, add few room sids. We will be happy to take a look.

**Comment by voigtd** [comment]
@anna-vasilko Gotcha - reason I was adding to this ticket is that its referenced in the last paragraph of this blog post: https://www.twilio.com/blog/best-practices-video-mobile-browsers

**Comment by voigtd** [comment]
@anna-vasilko Understood. The reason I was adding to this ticket is that its referenced in the last paragraph of this blog post: https://www.twilio.com/blog/best-practices-video-mobile-browsers

**Comment by davidfritsche17** [comment]
Just a note to confirm that the latest version of Mac Safari also had an audio challenge for two of our users today.  Here's the browser:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15

There were 5 people in a meeting and two could not hear one of the callers.   Both users were on Mac Safari.  This is the same behavior we had on the iPad reported above.

We are now forced to block Safari completely due to this issue continuing for months, appearing to be fixed and then reoccurring.  This is not a twilio issue, it's just Safari.

**Comment by davidfritsche17** [comment]
Thank you idelgago, 

Here's some additional information:
I know this is on iOS, but we just confirmed a related issue with Macbook Mac OS and the latest version of Safari.  Our user was in a meeting and received a Message on the message app.   Their audio stopped.

**Comment by satyen95** [comment]
@idelgado I'm still facing issue with localAudiotrack only on iOS Safari (current version iOS 14.7.1 & twilio-video 2.15.3) user audio is not audbile to others.. have already tried pause and play audiotrack but doesn't help.. the audio is not audible from start itself and toggle audio doesn't help either, sometimes when I lock my phone and unlock the audio is audible to others but

**Comment by cindyloo** [comment]
I'm experience static-y, inaudible audio via iOS Safari 14.7.1 and twilio-video 2.7.2

**Comment by ixit-ken-okazaki** [comment]
If you just want to watch on your iPhone, if you turn off the microphone
I can't hear the remote audio.

--iPhone 8 plus
--IOS 14.7.1
--Safari 14.1.2

**Comment by ixit-ken-okazaki** [comment]
If I watch a remote livestream on my iPhone.
I can't hear remote audio when the microphone is off.

--iPhone8plus
--IOS 14.7.1
--Safari 14.1.2

**Comment by ixit-ken-okazaki** [comment]
@idelgado

If I watch a remote livestream on my iPhone.
I can't hear remote audio when the microphone is off.

--iPhone8plus
--IOS 14.7.1
--Safari 14.1.2

**Comment by NikhilManapure** [comment]
@idelgado facing same issue on  iOS 14.7.1 & twilio-video 2.15.3

**Comment by satyen95** [comment]
Hi @cindyloo @ixit-ken-okazaki @NikhilManapure 
I have created a new issue you can mention your issues there.
https://github.com/twilio/twilio-video.js/issues/1564#issue-989959736
